using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace XIVChecklist.Data.Migrations
{
    public partial class TripleTriad : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "CardTasks",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    CategoryId = table.Column<int>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    Rank = table.Column<int>(nullable: false),
                    NPCName = table.Column<string>(nullable: true),
                    OtherMethods = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CardTasks", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Category_CardTasks",
                        column: x => x.CategoryId,
                        principalTable: "Category",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "OpponentTasks",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    CategoryId = table.Column<int>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    Zone = table.Column<string>(nullable: true),
                    Location = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OpponentTasks", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Category_OpponentTasks",
                        column: x => x.CategoryId,
                        principalTable: "Category",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "CardTasks",
                columns: new[] { "Id", "CategoryId", "NPCName", "Name", "OtherMethods", "Rank" },
                values: new object[,]
                {
                    { 94, 242, "Mimidoa", "Siren Card", "pve: Pharos Sirius", 2 },
                    { 161, 242, "Indolent Imperial", "Nero tol Scaeva Card", "", 3 },
                    { 160, 242, "Mogmill", "Moglin Card", "", 3 },
                    { 159, 242, "", "Mistbeard Card", "pve: Hullbreaker Isle (Hard)", 3 },
                    { 158, 242, "", "Mist Dragon Card", "pve: The Burn", 3 },
                    { 157, 242, "Midnight Dew", "Matoya Card", "", 3 },
                    { 156, 242, "", "Manxome Molaa Ja Ja Card", "pve: The Wanderer's Palace (Hard)", 3 },
                    { 155, 242, "", "Mammoth Card", "FATE: Wham, Bam, Thank You, Mammoth", 3 },
                    { 154, 242, "Ogodei", "Magnai Card", "", 3 },
                    { 153, 242, "", "Magitek Sky Armor Card", "Pack: Imperial", 3 },
                    { 152, 242, "", "Magitek Predator Card", "Pack: Imperial", 3 },
                    { 151, 242, "Lamlyn", "Lyna Card", "", 3 },
                    { 150, 242, "Masatsuchi", "Lupin Card", "", 3 },
                    { 149, 242, "Wawalago", "Lucia goe Junius Card", "", 3 },
                    { 148, 242, "Botan", "Louhi Card", "FATE: Louhi on Ice", 3 },
                    { 147, 242, "", "Leannan Sith", "Pack: Dream", 3 },
                    { 146, 242, "", "Lava Scorpion Card", "pve: Sohm Al (Hard)", 3 },
                    { 145, 242, "", "Lakshmi Card", "pve: Emanation, Emanation (Extreme)", 3 },
                    { 144, 242, "", "Kuribu Card", "pve: The Lost City of Amdapor (Hard)", 3 },
                    { 143, 242, "", "Kraken Card", "pve: Sastasha (Hard)", 3 },
                    { 162, 242, "Buscarron, Vorsaile Heuloix", "Papalymo & Yda Card", "", 3 },
                    { 163, 242, "Botan", "Pazuzu Card", "", 3 },
                    { 164, 242, "", "Penthesilea Card", "FATE: Lost Epic in The Ring of Fire", 3 },
                    { 165, 242, "", "Philia Card", "pve: Holminster Switch; Pack: Dream", 3 },
                    { 185, 242, "Fufulupa, Hab", "Thancred Card", "", 3 },
                    { 184, 242, "", "Suzaku Card", "pve: Hell's Kier, Hell's Kier (Extreme)", 3 },
                    { 183, 242, "", "Susano Card", "pve: The Pool of Tribute, The Pool of Tribute (Extreme)", 3 },
                    { 182, 242, "", "Strix Card", "pve: The Great Gubal Library (Hard)", 3 },
                    { 181, 242, "", "Storge Card", "pve: Malikah's Well; Pack: Dream", 3 },
                    { 180, 242, "", "Seiryu", "pve: The Wreath of Snakes, The Wreath of Snakes (Extreme)", 3 },
                    { 179, 242, "", "Seeker of Solitude", "pve: The Grand Cosmos", 3 },
                    { 178, 242, "Munglig", "Sadu Card", "", 3 },
                    { 177, 242, "Seika, Tapklix", "Roundrox Card", "", 3 },
                    { 142, 242, "Master Mogzin", "Kal Myhk Card", "", 3 },
                    { 176, 242, "", "Roland Card", "Seasonal: Make it Rain 2017: 1000", 3 },
                    { 174, 242, "Buscarron, Landenel", "Raya-O-Senna & A-Ruhn-Senna Card", "TTT: 4800", 3 },
                    { 173, 242, "Kaizan", "Rasho Card", "", 3 },
                    { 172, 242, "", "Qitian Dasheng Card", "pve: The Swallow's Compass", 3 },
                    { 171, 242, "Hetsukaze", "Provinence Watcher Card", "FATE: Crystalline Provenence", 3 },
                    { 170, 242, "", "Prometheus Card", "pve: The Ghimlyt Dark", 3 },
                    { 169, 242, "", "Progenitrix Card", "pve: Pharos Sirius (Hard)", 3 },
                    { 168, 242, "Swift", "Pipin Tarupin Card", "Pack: Mythril", 3 },
                    { 167, 242, "", "Phoebad Card", "FATE: Tall Tale in The Lochs", 3 },
                    { 166, 242, "Klynthota", "Phlegethon Card", "pve: Labyrinth of the Ancients", 3 },
                    { 175, 242, "", "Rofocale Card", "pve: The Royal City of Rabanastre", 3 },
                    { 186, 242, "", "The Griffin Card", "pve: Baelsar's Wall", 3 },
                    { 141, 242, "", "Julyan Manderville Card", "TTT: 14400", 3 },
                    { 139, 242, "Swift", "Ifrit Card", "pve: The Bowl of Embers (Hard), The Bowl of Embers (Extreme)", 3 },
                    { 114, 242, "Nigen", "Cirina Card", "", 3 },
                    { 113, 242, "", "Charibert Card", "pve: The Vault", 3 },
                    { 112, 242, "", "Calcabrina Card", "pve: The Antitower", 3 },
                    { 111, 242, "", "Byblos Card", "pve: The Great Gubal Library", 3 },
                    { 110, 242, "", "Byakko Card", "pve: The Jade Stoa and The Jade Stoa (Extreme)", 3 },
                    { 109, 242, "Nell Half-full", "Brendt, Brennan, & Bremondt Card", "", 3 },
                    { 108, 242, "Linu Vali", "Brachiosaur Card", "Pack: Mythril", 3 },
                    { 107, 242, "", "Belladonna Card", "pve: Saint Mocianne's Arboretum", 3 },
                    { 106, 242, "Sezul Totoloc, Ourdilic", "Behemoth Card", "Pack: Bronze", 3 },
                    { 105, 242, "Hachinan", "Asahi sas Brutus Card", "", 3 },
                    { 104, 242, "House Fortemps Manservant", "Artoirel de Fortemps Card", "", 3 },
                    { 103, 242, "Umber Torrent", "Arenvald Lentinus Card", "", 3 },
                    { 102, 242, "Ironwork's Hand", "Alpha Card", "", 3 },
                    { 101, 242, "", "Alexander Prime Card", "pve: Alexander - The Soul of the Creator", 3 },
                    { 100, 242, "", "Yukinko Card", "FATE: Eternity", 2 },
                    { 99, 242, "Yellow Moon", "Yugiri Mistwalker Card", "", 2 },
                    { 98, 242, "Mogmill", "Vanu Vanu Card", "", 2 },
                    { 97, 242, "Helmhart", "Ultros & Typhon Card", "pve: The Dragon's Neck", 2 },
                    { 96, 242, "Yusui", "Tansui Card", "", 2 },
                    { 115, 242, "Voracious Vath, Vath Deftarm", "Coeurlregina Card", "Pack: Mythril", 3 },
                    { 116, 242, "Marielle", "Count Edmont de Fortemps Card", "", 3 },
                    { 117, 242, "", "Curator Card", "The Fractal Continuum", 3 },
                    { 118, 242, "", "Darkscale Card", "FATE: Mogicide, Rastaban Vibration", 3 },
                    { 138, 242, "", "Hrodric Poisontongue Card", "pve: The Drowned City of Skalla", 3 },
                    { 137, 242, "", "Hiruko Card", "pve: Heaven on High", 3 },
                    { 136, 242, "Idle Imperial", "Hilda Card", "", 3 },
                    { 135, 242, "", "Haurchefant Card", "Achievement: Triple Team III", 3 },
                    { 134, 242, "", "Happy Bunny Card", "Eureka: SIlver", 3 },
                    { 133, 242, "", "Grynewaht Card", "pve: Doma Castle", 3 },
                    { 132, 242, "", "Griffin Card", "pve: The Dusk Vigil", 3 },
                    { 131, 242, "Vorsaile Heuloix", "Good King Moggle Mog XII Card", "pve: Thornmarch (Hard), Thornmarch (Extreme)", 3 },
                    { 130, 242, "Ruhtwyda of the Three Hearts, King Elmer III, Hab", "Godbert Manderville Card", "TTT: 9600", 3 },
                    { 140, 242, "Grewenn", "Jongleurs of Eulmore Card", "", 3 },
                    { 129, 242, "", "Gilgamesh & Enkidu Card", "pve: Battle on the Big Bridge; Pack: Mythril", 3 },
                    { 127, 242, "Marcette", "Garuda Card", "pve: The Howling Eye (Hard), The Howling Eye (Extreme)", 3 },
                    { 126, 242, "", "Formidable Card", "Kholusia: 200", 3 },
                    { 125, 242, "Imperial Deserter", "Fordola rem Lupis Card", "", 3 },
                    { 124, 242, "", "Ferdiad Card", "pve: Amdapor Keep (Hard)", 3 },
                    { 123, 242, "", "Fenrir Card", "pve: Snowcloak", 3 },
                    { 122, 242, "Gibrillont", "Estinien Card", "", 3 },
                    { 121, 242, "", "Eros Card", "pve: The Qitana Ravel; Pack: Dream", 3 },
                    { 120, 242, "House Fortemps Manservant", "Emmanellain de Fortemps Card", "", 3 },
                    { 119, 242, "", "Echidna Card", "pve: The Void Ark", 3 },
                    { 128, 242, "", "Genbu Card", "pve: Hell's Lid", 3 },
                    { 187, 242, "", "Tioman Card", "pve: Sohm Al", 3 },
                    { 188, 242, "Landenel, Trachtoum", "Titan Card", "pve: The Navel (Hard), The Navel (Extreme)", 3 },
                    { 189, 242, "", "Titania Card", "pve: The Dancing Plague, The Dancing Plague (Extreme); Pack: Dream", 3 },
                    { 256, 242, "", "Hraesvelgr Card", "pve: Sohr Khai", 5 },
                    { 255, 242, "Isobe", "Hisui and Kurenai Card", "", 5 },
                    { 254, 242, "Hab, Helmhart", "Hildibrand & Nashu Mhakaracca Card", "", 5 },
                    { 253, 242, "Kiuka", "Hien Card", "", 5 },
                    { 252, 242, "", "Hades Card", "pve: The Dying Gasp, The Minstrel's Ballad: Hades's Elegy", 5 },
                    { 251, 242, "", "Gosetsu", "Achievement: Triple-Decker VIII", 5 },
                    { 250, 242, "Indolent Imperial", "Gaius van Baelsar Card", "pve: The Praetorium", 5 },
                    { 249, 242, "", "Firion Card", "tournamet; pack: platinum", 5 },
                    { 248, 242, "", "Cloud Strife Card", "TTT: 1000000", 5 },
                    { 247, 242, "Klynthota", "Cloud of Darkness Card", "pve: World of Darkness", 5 },
                    { 246, 242, "", "Cecil Harvey Card", "tournament; pack: platinum", 5 },
                    { 245, 242, "Lewena", "Bartz Klauser Card", "pve: Battle in the Big Keep; pack: mythril", 5 },
                    { 244, 242, "King Elmer III", "Bahamut Card", "", 5 },
                    { 243, 242, "", "Ardbert Card", "Achievement: Triple Team VIII", 5 },
                    { 242, 242, "", "Archbishop Thordan VII Card", "pve: The Minstrel's Ballad: Thordan's Reign", 5 },
                    { 241, 242, "", "Archaeotania", "pack: dream", 5 },
                    { 240, 242, "", "9S", "pve: The Copied Factory", 5 },
                    { 239, 242, "Imperial Soldier", "Yotsuyu Card", "", 4 },
                    { 238, 242, "Klynthota", "Xande Card", "pve: Syrcus Tower", 4 },
                    { 257, 242, "Vorsaile Heuloix", "Kan-E-Senna Card", "", 5 },
                    { 258, 242, "Tataru", "Lightning Card", "tournament; pack: platinum", 5 },
                    { 259, 242, "R'ashaht Rhiki, Mordyn", "Merlwyb Bloefhiswyn Card", "", 5 },
                    { 260, 242, "", "Midgardsormr Card", "Achievement: Triple-Decker IV", 5 },
                    { 280, 242, "", "Zenos yae Galvus Card", "pve: Ala Mhigo", 5 },
                    { 279, 242, "Hokushin", "Yojimbo & Daigaro Card", "", 5 },
                    { 278, 242, "", "Yiazmat Card", "pve: The Ridorana Lighthouse", 5 },
                    { 277, 242, "", "Warrior of Light Card", "pack: gold", 5 },
                    { 276, 242, "", "Vaan Card", "Achievement: Wheel of Fortune V", 5 },
                    { 275, 242, "", "Ultima, the High Seraph Card", "pve: The Orbonne Monastery", 5 },
                    { 274, 242, "", "Tidus Card", "tournament; pack: platinum", 5 },
                    { 273, 242, "Lewena, Hall Overseer", "Terra Branford Card", "pve: The Dragon's Neck", 5 },
                    { 272, 242, "Mero Roggo", "Stormblood Alphinaud and Alisaie Card", "", 5 },
                    { 237, 242, "", "Vidofnir Card", "Achievement: Triple Decker V", 4 },
                    { 271, 242, "", "Squall Leonhart Card", "Achievement: Triple Team II", 5 },
                    { 269, 242, "", "Shantotto Card", "Achievement: Kumite Kumite Kumite", 5 },
                    { 268, 242, "Idle Imperial", "Regula van Hydrus Card", "pack: imperial", 5 },
                    { 267, 242, "", "Raubahn and Pipin Card", "ttt: 400000", 5 },
                    { 266, 242, "Swift", "Raubahn Aldynn Card", "", 5 },
                    { 265, 242, "Lewena", "Onion Knight Card", "pve: World of Darkness; pack: mythril", 5 },
                    { 264, 242, "", "Omega Card", "pve: Alphascape V3.0, V4.0", 5 },
                    { 263, 242, "", "Noctis Lucis Caelum Card", "Seasonal: A Nocturne for Heroes: 10000", 5 },
                    { 262, 242, "", "Nidhogg Card", "pve: The Aery", 5 },
                    { 261, 242, "", "Nanamo Ul Namo Card", "ttt: 400000; pack: platinum", 5 },
                    { 270, 242, "", "Sophia Card", "pve: Containment Bay P1T6, Containment Bay P1T6 (Extreme)", 5 },
                    { 236, 242, "Klynthota", "Unei & Doga Card", "", 4 },
                    { 235, 242, "", "Ultima Weapon Card", "pve: The Minstrel's Ballad: Ultima's Bane; pack: gold, platinum", 4 },
                    { 234, 242, "", "Tsukuyomi Card", "pve: The Minstrel's Ballad: Tsukuyomi's Pain", 4 },
                    { 209, 242, "Gyoei", "Great Gold Whisker Card", "", 4 },
                    { 208, 242, "", "Gigi Card", "Seasonal: Make It Rain 2017: 18000", 4 },
                    { 207, 242, "", "F'lhaminn Card", "TTT: 20000", 4 },
                    { 206, 242, "", "Diabolos Hollow Card", "pve: Dun Scaith", 4 },
                    { 205, 242, "Sezul Totoloc", "Cid Garlond Card", "Gold Triad Card", 4 },
                    { 204, 242, "", "Calofisteri Card", "pve: The Weeping City of Mhach", 4 },
                    { 203, 242, "Tapklix", "Brute Justice Card", "pve: Alexander - The Burden of the Son", 4 },
                    { 202, 242, "Linu Vali", "Bismarck Card", "pve: The Limitless Blue (Hard), The Limitless Blue (Extreme)", 4 },
                    { 201, 242, "Yayake", "Aymeric Card", "", 4 },
                    { 210, 242, "Kikimo", "Hancock Card", "", 4 },
                    { 200, 242, "", "Armored Weapon Card", "pack: Imperial", 4 },
                    { 198, 242, "Joellaut, Swift", "Alphinaud & Alisaie Card", "", 4 },
                    { 197, 242, "Marcechamp", "Ysayle Card", "", 3 },
                    { 196, 242, "Gegeruju, R'ashaht Rhiki", "Y'shtola Card", "", 3 },
                    { 195, 242, "", "Waukkeon Card", "pve: Neverreap", 3 },
                    { 194, 242, "", "Vicegerent to the Warden Card", "pve: The Sunken Temple of Qarn (Hard)", 3 },
                    { 193, 242, "Mogmill", "Vedrfolnir Card", "Pack: Mythril", 3 },
                    { 192, 242, "Ruhtwyda of the Three Hearts, Tataru", "Urianger Card", "Pack: Silver", 3 },
                    { 191, 242, "", "Tozol Huatotl Card", "pve: Xelphatol", 3 },
                    { 190, 242, "", "Tokkapchi Card", "pve: Saint Mocianne's Arboretum (Hard)", 3 },
                    { 199, 242, "", "Argath Thadalfus Card", "pve: The Royal City of Rabanastre", 4 },
                    { 95, 242, "Piralnaut", "Succubus Card", "pve: Haukke Manor, Haukke Manor (Hard)", 2 },
                    { 211, 242, "", "Heavensward Thancred Card", "Achievement: Triple Team V", 4 },
                    { 213, 242, "", "Innocence Card", "pve: The Crown of the Immaculate, The Crown of the Immaculate (Extreme); pack: Dream", 4 },
                    { 233, 242, "Idle Imperial", "Tiamat Card", "", 4 },
                    { 232, 242, "", "Stormblood Gilgamesh Card", "pve: Kugane Ohashi", 4 },
                    { 231, 242, "", "Shiva Card", "pve: Akh Afah Amphitheatre (Hard), Akh Afah Amphitheatre (Extreme); pack: platinum", 4 },
                    { 230, 242, "", "Shinryu Card", "pve: The Royal Menagerie", 4 },
                    { 229, 242, "Hargra", "Shadowbringers Y'shtola Card", "", 4 },
                    { 228, 242, "", "Shadowbringers Urianger Card", "Achievement: Triple-decker IX", 4 },
                    { 227, 242, "", "Sephirot Card", "pve: Containment Bay S1T7", 4 },
                    { 226, 242, "", "Senor Sabotender Card", "TTT: 200000", 4 },
                    { 225, 242, "Vath Deftarm", "Ravana Card", "pve: Thok ast Thok (Hard), Thok ast Thok (Extreme)", 4 },
                    { 212, 242, "", "Heavensward Y'shtola Card", "Achievement: Triple-Decker VI", 4 },
                    { 224, 242, "Grewenn", "Ran'jit Card", "", 4 },
                    { 222, 242, "", "Oracle of Light", "pack: dream", 4 },
                    { 221, 242, "Landenel", "Odin Card", "pve: Urth's Fount; pack: mythril", 4 },
                    { 220, 242, "Flichoirel the Lordling", "Nael van Darnus Card", "", 4 },
                    { 219, 242, "Gegeruju", "Minfilia Card", "pack: silver", 4 },
                    { 218, 242, "", "Lyse Card", "Achievement: Triple-decker VI", 4 },
                    { 217, 242, "Rowena", "Louisoix Leveilleur Card", "", 4 },
                    { 216, 242, "R'ashaht Rhiki", "Leviathan Card", "pve: The Whorleater (Hard), The Whorleater (Extreme)", 4 },
                    { 215, 242, "", "Lahabrea Card", "pack: Silver Triad Card, Platinum Triad Card", 4 },
                    { 214, 242, "", "Krile Card", "Achievement: Triple Team VII", 4 },
                    { 223, 242, "Vorsaile Heuloix", "Ramuh Card", "pve: The Striking Tree (Hard), The Striking Tree (Extreme)", 4 },
                    { 281, 242, "", "Zidane Tribal Card", "pack: gold", 5 },
                    { 282, 242, "", "Zurvan Card", "pve: Containment Bay Z1T9, Containment Bay Z1T9 (Extreme)", 5 },
                    { 92, 242, "Hargra", "Runar Card", "", 2 },
                    { 25, 242, "", "Mossling Card", "TTT: 840", 1 },
                    { 26, 242, "Gyoei", "Namazu Card", "", 1 },
                    { 27, 242, "", "Opo-opo Card", "TTT: 600", 1 },
                    { 28, 242, "Eo Sigun", "Porxie", "", 1 },
                    { 29, 242, "Roger", "Pudding Card", "Pack: Bronze", 1 },
                    { 30, 242, "", "Sabotender Card", "Starter", 1 },
                    { 31, 242, "Baderon", "Sahagin Card", "PvE: Sastasha, Sastasha (Hard)", 1 },
                    { 32, 242, "Triple Triad Master, Guhtwint of the Three Diamonds", "Spriggan Card", "Pack: Bronze", 1 },
                    { 33, 242, "", "Stormblood Tataru Taru", "TTT: 96000", 1 },
                    { 34, 242, "Maisenta", "Sylph Card", "Pack: Silver", 1 },
                    { 35, 242, "Tataru", "Tataru Taru Card", "Pack: Silver", 1 },
                    { 36, 242, "Memeroon", "Tonberry Card", "PvE: The Wanderer's Palace, The Wanderer's Palace (Hard)", 1 },
                    { 37, 242, "", "Wanyudo and Katasharin Card", "PvE: Heaven on High", 1 },
                    { 38, 242, "", "Adamantoise Card", "TTT: 840", 2 },
                    { 39, 242, "Garima", "Ananta Card", "", 2 },
                    { 40, 242, "Isobe", "Ango Card", "", 2 },
                    { 41, 242, "Elaisse", "Archaeornis Card", "", 2 },
                    { 42, 242, "Baderon", "Baderon Tenfingers Card", "Pack: Gold", 2 },
                    { 43, 242, "Voracious Vath", "Bandersnatch Card", "", 2 },
                    { 24, 242, "Jonas of the Three Spades, Trachtoum", "Moogle Card", "TTT: 840", 1 },
                    { 22, 242, "", "Mandragora Card", "Starter", 1 },
                    { 21, 242, "", "Magitek Death Claw Card", "Pack: Bronze", 1 },
                    { 20, 242, "Ibenart", "Lord and Lady Chai Card", "", 1 },
                    { 93, 242, "Guhtwint of the Three Diamonds, Aurifort of the Three Clubs", "Scarface Bugaal Ja Card", "Pack: Bronze", 2 },
                    { 1, 242, "Ourdilic", "Ahriman Card", "PvE: Dzemael Darkhold", 1 },
                    { 2, 242, "Memeroon", "Amalj'aa Card", "Pack: Silver", 1 },
                    { 3, 242, "Glynard", "Amaro Card", "", 1 },
                    { 4, 242, "Wyra Lyegha", "Apkallu Card", "", 1 },
                    { 5, 242, "", "Bomb Card", "Starter", 1 },
                    { 6, 242, "Triple Triad Master, Jonas of the Three Spades, Guhtwint of the Three Diamonds", "Chocobo Card", "TTT: 600", 1 },
                    { 7, 242, "Maisenta, Wymond", "Coblyn Card", "Pack: Bronze", 1 },
                    { 8, 242, "", "Coeurl Card", "Starter", 1 },
                    { 44, 242, "Mimidoa, Sezul Totoloc", "Biggs & Wedge Card", "", 2 },
                    { 9, 242, "Flichoirel the Lordling", "Colibri Card", "", 1 },
                    { 11, 242, "", "Dodo Card", "Starter", 1 },
                    { 12, 242, "Drery", "Evil Weapon Card", "", 1 },
                    { 13, 242, "Noes", "Gaelicat Card", "", 1 },
                    { 14, 242, "Mother Miounne, Aurifort of the Three Clubs", "Goobbue Card", "Pack: Bronze", 1 },
                    { 15, 242, "", "Hobgoblin", "Pack: Dream", 1 },
                    { 16, 242, "Jonas of the Three Spades, Joellaut", "Ixal Card", "Pack: Silver", 1 },
                    { 17, 242, "Hokushin", "Karakuri Hanya Card ", "", 1 },
                    { 18, 242, "", "Kobold Card", "Pack: Silver", 1 },
                    { 19, 242, "Masatsuchi", "Koja Card", "", 1 },
                    { 10, 242, "Dominiac", "Deepeye Card", "", 1 },
                    { 45, 242, "Ourdilic", "Blue Dragon Card", "PvE: The Stone Vigil, Stone Vigil (Hard)", 2 },
                    { 23, 242, "Roger", "Morbol Card", "PvE: Aurum Vale", 1 },
                    { 47, 242, "", "Chapuli Card", "TTT: 1200", 2 },
                    { 72, 242, "Marielle", "Laniaitte de Haillenarte Card", "", 2 },
                    { 73, 242, "", "Liquid Flame Card", "Pack: Bronze", 2 },
                    { 74, 242, "Indolent Imperial", "Livia sas Junius Card", "pve: Castrum Meridianum", 2 },
                    { 75, 242, "Wymond", "Lolorito Nanarito Card", "", 2 },
                    { 76, 242, "Prideful Stag", "Lost Lamb Card", "", 2 },
                    { 77, 242, "Ercanbald", "M'naago Card", "", 2 },
                    { 78, 242, "Hall Overseer", "Magitek Colossus Card", "", 2 },
                    { 80, 242, "", "Magitek Vanguard Card", "Pack: Imperial", 2 },
                    { 81, 242, "Memeroon", "Memeroon Card", "", 2 },
                    { 71, 242, "Kotokaze", "Kotokaze Card", "", 2 },
                    { 82, 242, "Momodi", "Momodi Modi Card", "Pack: Gold", 2 },
                    { 84, 242, "F'hobhas", "Mutamix Bubblypots Card", "", 2 },
                    { 85, 242, "", "Muud Suud Card", "TTT: 6000", 2 },
                    { 86, 242, "Eo Sigun", "Nu Mou", "", 2 },
                    { 87, 242, "Laniaitte", "Paissa Card", "", 2 },
                    { 88, 242, "Seika", "Poroggo Card", "", 2 },
                    { 89, 242, "Garima", "Qiqirn Meateater Card", "", 2 },
                    { 90, 242, "Indolent Imperial", "Rhitahtyn sas Arvina Card", "pve: Cape Westwind", 2 },
                    { 46, 242, "Mordyn", "Carvallain de Gorgagne Card", "", 2 },
                    { 91, 242, "O'kalkaya", "Rhoswen Card", "", 2 },
                    { 83, 242, "Mother Miounne", "Mother Miounne Card", "Pack: Gold", 2 },
                    { 70, 242, "Tsuzura", "Kojin Card", "", 2 },
                    { 79, 242, "", "Magitek Gunship Card", "Pack: Imperial", 2 },
                    { 49, 242, "Seika", "Crawler Card", "", 2 },
                    { 48, 242, "Fufulupa", "Chimera Card", "pve: Cutter's Cry", 2 },
                    { 69, 242, "", "Iguana", "Pack: Dream", 2 },
                    { 50, 242, "", "Delivery Moogle Card", "", 2 },
                    { 51, 242, "Buscarron", "Demon Wall Card", "pve: Amdapor Keep, Amdapor Keep (Hard)", 2 },
                    { 52, 242, "Laniaitte", "Dhalmel Card", "", 2 },
                    { 53, 242, "Hetsukaze", "Dvergr Card", "FATE: Duty-Free", 2 },
                    { 54, 242, "Hetsukaze", "Ejika Tsunjika Card", "", 2 },
                    { 56, 242, "Gyulf Uin", "Feo Ul Card", "", 2 },
                    { 57, 242, "Marcette, Piralnaut", "Frixio Card", "", 2 },
                    { 58, 242, "", "Fuath", "Pack: Dream", 2 },
                    { 55, 242, "Vath Deftarm", "Fat Chocobo Card", "FATE: Special Tarasque Force", 2 },
                    { 60, 242, "Elaisse", "Gibrillont Card", "", 2 },
                    { 68, 242, "House Fortemps Manservant", "Honoroit Card", "", 2 },
                    { 59, 242, "Helmhart, Rowena", "Gerolt Card", "Pack: Gold", 2 },
                    { 66, 242, "", "Hatamoto Card", "pve: Heaven on High", 2 },
                    { 65, 242, "", "Guidance Node Card", "pve: The Fractal Continuum (Hard)", 2 },
                    { 64, 242, "Saushs Koal", "Grenoldt Card", "", 2 },
                    { 67, 242, "", "Hoary Boulder & Coultenet Card", "Pack: Gold", 2 },
                    { 62, 242, "Mogmill", "Gnath Card", "", 2 },
                    { 61, 242, "Drery", "Gigantender Card", "", 2 },
                    { 63, 242, "", "Gold Saucer Attendant Card", "Seasonal: Make it Rain 2017: 500", 2 }
                });

            migrationBuilder.InsertData(
                table: "OpponentTasks",
                columns: new[] { "Id", "CategoryId", "Location", "Name", "Zone" },
                values: new object[,]
                {
                    { 34, 243, "The Ruby Sea (28.5,16.4)", "Tsuzura", "The Ruby Sea" },
                    { 26, 243, "Kugane  (14.4-11.2)", "Hokushin", "Kugane" },
                    { 27, 243, "Chocobo Forest (31,23)", "Marcechamp", "The Dravanian Forelands" },
                    { 28, 243, "Battlehall (3.7,3.3)", "Prideful Stag", "Triple Triad Battlehall" },
                    { 29, 243, "Il Mheg (22,3)", "Eo Sigun", "Norvrandt" },
                    { 30, 243, "Vira Nilya (28.2-19.9)", "Garima", "The Fringes" },
                    { 31, 243, "Drybone (20,21)", "Helmhart", "Eastern Thanalan" },
                    { 32, 243, "Shiokaze Hostelry (10.2,10.2)", "Kotokaze", "Kugane" },
                    { 33, 243, "Nine Ivies (17,26)", "Piralnaut", "East Shroud" },
                    { 35, 243, "Rasen Kaikyo (21.7-7.9)", "Ushiogi", "The Ruby Sea" },
                    { 45, 243, "Pier 1  (8.0-13.6)", "Hetsukaze", "Kugane" },
                    { 37, 243, "Twinpools (16,22)", "Dominiac", "Coerthas Western Highlands" },
                    { 38, 243, "Rak'tika Greatwood (18.6, 26)", "Hargra", "Norvrandt" },
                    { 39, 243, "Various (Inside Fortemps Manor)", "House Fortemps Manservant", "Fortemps Manor" },
                    { 40, 243, "The Ruby Sea (22.3,8.6)", "Kaizan", "The Ruby Sea" },
                    { 41, 243, "Lakeland (35.4, 20.2)", "Lamlyn", "Norvrandt" },
                    { 42, 243, "Various", "Linu Vali", "The Sea of Clouds" },
                    { 43, 243, "Old Gridania (10,5)", "Noes", "Gridania" },
                    { 44, 243, "Pier 1  (7.8-14.7)", "Botan", "Kugane" },
                    { 25, 243, "Horizon's Edge (22,17)", "Fufulupa", "Western Thanalan" },
                    { 36, 243, "Sakazuki (31.6,37.1)", "Yusui", "The Ruby Sea" },
                    { 24, 243, "Limsa Lominsa Upper Decks (11,11)", "Baderon", "Limsa Lominsa" },
                    { 2, 243, "Card Square (4,7)", "Jonas of the Three Spades", "The Gold Saucer" },
                    { 22, 243, "Cedarwood (35,15)", "Trachtoum", "Lower La Noscea" },
                    { 46, 243, "Gamma Quadrant (28,31)", "Idle Imperial", "Azys La" },
                    { 3, 243, "Oakwood (14,24)", "Memeroon", "Upper La Noscea" },
                    { 4, 243, "Black Brush (19,20)", "Roger", "Central Thanalan" },
                    { 5, 243, "The Tempest (31.6, 17.3)", "Saushs Koal", "Norvrandt" },
                    { 6, 243, "Battlehall (3.3,3.3)", "Wyra \"Greenhands\" Lyehga", "Triple Triad Battlehall" },
                    { 7, 243, "Black Brush (23,13)", "F'hobhas", "Central Thanalan" },
                    { 8, 243, "The Wandering Stairs (10.8-15.2)", "Glynard", "The Crystarium" },
                    { 9, 243, "Card Square (4,7)", "Guhtwint of the Three Diamonds", "The Gold Saucer" },
                    { 10, 243, "New Gridania (11,11)", "Maisenta", "Gridania" },
                    { 23, 243, "Card Square (4,7)", "Aurifort of the Three Clubs", "The Gold Saucer" },
                    { 11, 243, "Idyllshire (6,7)", "Seika", "The Dravanian Hinterlands" },
                    { 13, 243, "Amh Araeng (12, 17)", "Drery", "Norvrandt" },
                    { 14, 243, "Rhalgr's Reach(9.8,9.8)", "Ercanbald", "Rhalgr's Reach" },
                    { 15, 243, "Yuzuka Manor (15.7,31.9)", "Gyoei", "Yanxia" },
                    { 16, 243, "Il Mheg (16.1, 30.6)", "Gyuf Uin", "Norvrandt" },
                    { 17, 243, "Kholusia (19.1, 17.4)", "Ibenart", "Norvrandt" },
                    { 18, 243, "Whitebrim (13,15)", "Joellaut", "Coerthas Central Highlands" },
                    { 19, 243, "The Gods' Grip (25,35)", "Mimidoa", "Lower La Noscea" },
                    { 20, 243, "Steps of Nald (11,9)", "Momodi", "Ul'dah" },
                    { 21, 243, "New Gridania (11,13)", "Mother Miounne", "Gridania" },
                    { 12, 243, "Steps of Nald (9,8)", "Wymond", "Ul'dah" },
                    { 47, 243, "Camp Tranquil (16,28)", "Landenel", "South Shroud" },
                    { 94, 243, "Entrance Square (4,6)", "Lewena", "The Gold Saucer" },
                    { 49, 243, "Limsa Lominsa Upper Decks (11,7)", "Mordyn", "Limsa Lominsa" },
                    { 75, 243, "The Yarn (30.7, 31.8)", "Ironworks Hand", "Rhalgr's Reach" },
                    { 76, 243, "Card Square (3,7)", "King Elmer III", "The Gold Saucer" },
                    { 77, 243, "Sorrel Haven (16,18)", "Marcette", "Central Shroud" },
                    { 78, 243, "Idyllshire (6,7)", "Midnight Dew", "The Dravanian Hinterlands" },
                    { 79, 243, "Sohm Al Summit (28,35)", "Mogmill", "The Churning Mists" },
                    { 80, 243, "Dotharl Khaa", "Munglig", "The Azim Steppe" },
                    { 81, 243, "The Azim Steppe (31.9,11.5)", "Nigen", "The Azim Steppe" },
                    { 82, 243, "Limsa Lominsa Lower Decks (13,12)", "R'ashaht Rhiki", "Limsa Lominsa" },
                    { 83, 243, "Card Square (3,7)", "Ruhtwyda of the Three Hearts", "The Gold Saucer" },
                    { 74, 243, "The Lochs (32.8,30.1)", "Imperial Deserter (The Lochs)", "The Lochs" },
                    { 84, 243, "The Saltery", "Umber Torrent", "The Lochs" },
                    { 86, 243, "Bloodshore (35,30)", "Gegeruju", "Eastern La Noscea" },
                    { 87, 243, "Sakazuki (32.9,37.5)", "Kikimo", "The Ruby Sea" },
                    { 88, 243, "Doman Enclave (5.5,4.5)", "Kiuka", "Doman Enclave" },
                    { 89, 243, "North Silvertear (30,13)", "Klynthota", "Mor Dhona" },
                    { 90, 243, "Cloudtop (15,37)", "Marielle", "The Sea of Clouds" },
                    { 91, 243, "New Gridania (9,11)", "Vorsaile Heuloix", "Gridania" },
                    { 92, 243, "The Pillars (7,10)", "Elaisse", "Ishgard" },
                    { 93, 243, "Battlehall (3.5,3.5)", "Hall Overseer", "Triple Triad Battlehall" },
                    { 95, 243, "Sui-no-Sato (20.2,19.5)", "Isobe", "The Ruby Sea" },
                    { 85, 243, "The Smoldering Wastes (23,19)", "Voracious Vath", "Dravanian Forelands" },
                    { 73, 243, "Eulmore (12.5, 9.9)", "Grewenn", "Norvrandt" },
                    { 72, 243, "Battlehall (3.7,3.7)", "Flichoirel the Lordling", "Triple Triad Battlehall" },
                    { 71, 243, "Upper Paths (18,19)", "Buscarron", "South Shroud" },
                    { 50, 243, "Battlehall (3.3,3.7)", "Nell Half-Full", "Triple Triad Battlehall" },
                    { 51, 243, "Limsa Lominsa Upper Decks (12,13)", "O'kalkaya", "Limsa Lominsa" },
                    { 52, 243, "Greengrub Mudplots", "Redbill Storeboy", "Idyllshire" },
                    { 53, 243, "Steps of Nald (8,8)", "Swift", "Ul'dah" },
                    { 54, 243, "Ul'dah - Steps of Nald (7,12)", "Yayake", "Ul'dah" },
                    { 55, 243, "Ul'dah - Steps of Nald (14,13)", "Yellow Moon", "Ul'dah" },
                    { 56, 243, "Foundation (12,11)", "Gibrillont", "Ishgard" },
                    { 57, 243, "Sagolii Desert (24,40)", "Hab", "Southern Thanalan" },
                    { 58, 243, "The House of the Fierce (26.4,12.9)", "Hachinan", "Yanxia" }
                });

            migrationBuilder.InsertData(
                table: "OpponentTasks",
                columns: new[] { "Id", "CategoryId", "Location", "Name", "Zone" },
                values: new object[,]
                {
                    { 59, 243, "Mor Dhona (11,17)", "Indolent Imperial", "Mor Dhona" },
                    { 60, 243, "Cloudtop (16,37)", "Laniaitte", "The Sea of Clouds" },
                    { 61, 243, "Namai (29.5,20.2)", "Masatsuchi", "Yanxia" },
                    { 62, 243, "Idyllshire (15.6,28.8)", "Master Mogzin", "The Churning Mists" },
                    { 63, 243, "The Dawn Throne (22,20.7)", "Ogodei", "The Azim Steppe" },
                    { 64, 243, "Whitebrim (6,22)", "Ourdilic", "Coerthas Central Highlands" },
                    { 65, 243, "Fogfens (21,5)", "Rowena", "Mor Dhona" },
                    { 66, 243, "Peacegarden (24,23)", "Sezul Totoloc", "North Shroud" },
                    { 67, 243, "The Collectors' Quarter (21,18)", "Tapklix", "The Dravanian Hinterlands" },
                    { 68, 243, "Coerthas Central Highlands (26,17)", "Tataru", "Coerthas Central Highlands" },
                    { 69, 243, "Various", "Vath Deftarm", "The Dravanian Forelands" },
                    { 70, 243, "Limsa Lominsa Lower Decks (8,15)", "Wawalago", "Limsa Lominsa" },
                    { 48, 243, "The Ruling Quarter (12.7-36.8)", "Mero Roggo", "The Dravanian Hinterlands" },
                    { 1, 243, "Card Square (4,7)", "Triple Triad Master", "The Gold Saucer" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_CardTasks_CategoryId",
                table: "CardTasks",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_OpponentTasks_CategoryId",
                table: "OpponentTasks",
                column: "CategoryId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CardTasks");

            migrationBuilder.DropTable(
                name: "OpponentTasks");
        }
    }
}
