// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XIVChecklist.Data.Context;

namespace XIVChecklist.Data.Migrations
{
    [DbContext(typeof(XIVContext))]
    [Migration("20200108161412_CommonSeed")]
    partial class CommonSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("XIVChecklist.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Abbreviation");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Discipline");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "WAR",
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "PLD",
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "DRK",
                            Name = "Dark Knight"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "GNB",
                            Name = "Gunbreaker"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "WHM",
                            Name = "White Mage"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "SCH",
                            Name = "Scholar"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "AST",
                            Name = "Astrologist"
                        },
                        new
                        {
                            Id = 8,
                            Abbreviation = "RDM",
                            Name = "Red Mage"
                        },
                        new
                        {
                            Id = 9,
                            Abbreviation = "BLM",
                            Name = "Black Mage"
                        },
                        new
                        {
                            Id = 10,
                            Abbreviation = "BLU",
                            Name = "Blue Mage"
                        },
                        new
                        {
                            Id = 11,
                            Abbreviation = "SMN",
                            Name = "Summoner"
                        },
                        new
                        {
                            Id = 12,
                            Abbreviation = "MNK",
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 13,
                            Abbreviation = "SAM",
                            Name = "Samurai"
                        },
                        new
                        {
                            Id = 14,
                            Abbreviation = "NIN",
                            Name = "Ninja"
                        },
                        new
                        {
                            Id = 15,
                            Abbreviation = "DRG",
                            Name = "Dragoon"
                        },
                        new
                        {
                            Id = 16,
                            Abbreviation = "BRD",
                            Name = "Bard"
                        },
                        new
                        {
                            Id = 17,
                            Abbreviation = "DNC",
                            Name = "Dancer"
                        });
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Expansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Expansion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "A Realm Reborn"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Heavensward"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stormblood"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shadowbringers"
                        });
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.LeveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LeveType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Battlecraft"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tradecraft"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fieldcraft"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Flames"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Maelstrom"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Twin Adder"
                        });
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("ZoneId");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.PvEContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<int>("PvEContentTypeId");

                    b.Property<int>("iLevel");

                    b.HasKey("Id");

                    b.ToTable("PvEContent");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = 15,
                            Name = "Sastasha",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 2,
                            Level = 16,
                            Name = "The Tam-Tara Deepcroft",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 3,
                            Level = 17,
                            Name = "Copperbell Mines",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 4,
                            Level = 20,
                            Name = "Halatali",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 5,
                            Level = 24,
                            Name = "The Thousand Maws of Toto-Rak",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 6,
                            Level = 28,
                            Name = "Haukke Manor",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 7,
                            Level = 32,
                            Name = "Brayflox's Longstop",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 8,
                            Level = 35,
                            Name = "The Sunken Temple of Karn",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 9,
                            Level = 38,
                            Name = "Cutter's Cry",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 10,
                            Level = 41,
                            Name = "The Stone Vigil",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 11,
                            Level = 44,
                            Name = "Dzemael Darkhold",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 12,
                            Level = 47,
                            Name = "The Aurum Vale",
                            PvEContentTypeId = 1,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 13,
                            Level = 50,
                            Name = "Castrum Meridianum",
                            PvEContentTypeId = 1,
                            iLevel = 42
                        },
                        new
                        {
                            Id = 14,
                            Level = 50,
                            Name = "The Praetorium",
                            PvEContentTypeId = 1,
                            iLevel = 42
                        },
                        new
                        {
                            Id = 15,
                            Level = 50,
                            Name = "The Wanderer's Palace",
                            PvEContentTypeId = 1,
                            iLevel = 45
                        },
                        new
                        {
                            Id = 16,
                            Level = 50,
                            Name = "Amdapor Keep",
                            PvEContentTypeId = 1,
                            iLevel = 45
                        },
                        new
                        {
                            Id = 17,
                            Level = 50,
                            Name = "Pharos Sirius",
                            PvEContentTypeId = 1,
                            iLevel = 48
                        },
                        new
                        {
                            Id = 18,
                            Level = 50,
                            Name = "Copperbell Mines (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 48
                        },
                        new
                        {
                            Id = 19,
                            Level = 50,
                            Name = "Haukke Manor (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 48
                        },
                        new
                        {
                            Id = 20,
                            Level = 50,
                            Name = "The Lost City of Amdapor",
                            PvEContentTypeId = 1,
                            iLevel = 55
                        },
                        new
                        {
                            Id = 21,
                            Level = 50,
                            Name = "Halatali (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 55
                        },
                        new
                        {
                            Id = 22,
                            Level = 50,
                            Name = "Brayflox's Longstop (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 55
                        },
                        new
                        {
                            Id = 23,
                            Level = 50,
                            Name = "Hullbreaker Isle",
                            PvEContentTypeId = 1,
                            iLevel = 70
                        },
                        new
                        {
                            Id = 24,
                            Level = 50,
                            Name = "The Stone Vigil (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 70
                        },
                        new
                        {
                            Id = 25,
                            Level = 50,
                            Name = "The Tam-Tara-Deepcroft (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 70
                        },
                        new
                        {
                            Id = 26,
                            Level = 50,
                            Name = "Snowcloak",
                            PvEContentTypeId = 1,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 27,
                            Level = 50,
                            Name = "Sastasha (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 28,
                            Level = 50,
                            Name = "The Sunken Temple of Qarn (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 29,
                            Level = 50,
                            Name = "The Keeper of the Lake",
                            PvEContentTypeId = 1,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 30,
                            Level = 50,
                            Name = "The Wanderer's Palace (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 31,
                            Level = 50,
                            Name = "Amdapor Keep (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 32,
                            Level = 51,
                            Name = "The Dusk Vigil",
                            PvEContentTypeId = 1,
                            iLevel = 100
                        },
                        new
                        {
                            Id = 33,
                            Level = 53,
                            Name = "Sohm Al",
                            PvEContentTypeId = 1,
                            iLevel = 105
                        },
                        new
                        {
                            Id = 34,
                            Level = 55,
                            Name = "The Aery",
                            PvEContentTypeId = 1,
                            iLevel = 110
                        },
                        new
                        {
                            Id = 35,
                            Level = 57,
                            Name = "The Vault",
                            PvEContentTypeId = 1,
                            iLevel = 115
                        },
                        new
                        {
                            Id = 36,
                            Level = 59,
                            Name = "The Great Gubal Library",
                            PvEContentTypeId = 1,
                            iLevel = 120
                        },
                        new
                        {
                            Id = 37,
                            Level = 60,
                            Name = "The Aetherochemical Research Facility",
                            PvEContentTypeId = 1,
                            iLevel = 142
                        },
                        new
                        {
                            Id = 38,
                            Level = 60,
                            Name = "Neverreap",
                            PvEContentTypeId = 1,
                            iLevel = 145
                        },
                        new
                        {
                            Id = 39,
                            Level = 60,
                            Name = "The Fractal Continuum",
                            PvEContentTypeId = 1,
                            iLevel = 145
                        },
                        new
                        {
                            Id = 40,
                            Level = 60,
                            Name = "Saint Mocianne's Arboretum",
                            PvEContentTypeId = 1,
                            iLevel = 170
                        },
                        new
                        {
                            Id = 41,
                            Level = 60,
                            Name = "Pharos Sirius (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 170
                        },
                        new
                        {
                            Id = 42,
                            Level = 60,
                            Name = "The Antitower",
                            PvEContentTypeId = 1,
                            iLevel = 180
                        },
                        new
                        {
                            Id = 43,
                            Level = 60,
                            Name = "The Lost City of Amdapor (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 180
                        },
                        new
                        {
                            Id = 44,
                            Level = 60,
                            Name = "Sohr Khai",
                            PvEContentTypeId = 1,
                            iLevel = 200
                        },
                        new
                        {
                            Id = 45,
                            Level = 60,
                            Name = "Hullbreaker Isle (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 200
                        },
                        new
                        {
                            Id = 46,
                            Level = 60,
                            Name = "Xelphatol",
                            PvEContentTypeId = 1,
                            iLevel = 210
                        },
                        new
                        {
                            Id = 47,
                            Level = 60,
                            Name = "The Great Gubal Library (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 210
                        },
                        new
                        {
                            Id = 48,
                            Level = 60,
                            Name = "Baelsar's Wall",
                            PvEContentTypeId = 1,
                            iLevel = 230
                        },
                        new
                        {
                            Id = 49,
                            Level = 60,
                            Name = "Sohm Al (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 230
                        },
                        new
                        {
                            Id = 50,
                            Level = 61,
                            Name = "The Sirensong Sea",
                            PvEContentTypeId = 1,
                            iLevel = 240
                        },
                        new
                        {
                            Id = 51,
                            Level = 63,
                            Name = "Shisui of the Violet Tides",
                            PvEContentTypeId = 1,
                            iLevel = 245
                        },
                        new
                        {
                            Id = 52,
                            Level = 65,
                            Name = "Bardam's Mettle",
                            PvEContentTypeId = 1,
                            iLevel = 250
                        },
                        new
                        {
                            Id = 53,
                            Level = 67,
                            Name = "Doma Castle",
                            PvEContentTypeId = 1,
                            iLevel = 255
                        },
                        new
                        {
                            Id = 54,
                            Level = 69,
                            Name = "Castrum Abania",
                            PvEContentTypeId = 1,
                            iLevel = 260
                        },
                        new
                        {
                            Id = 55,
                            Level = 70,
                            Name = "Ala Mhigo",
                            PvEContentTypeId = 1,
                            iLevel = 280
                        },
                        new
                        {
                            Id = 56,
                            Level = 70,
                            Name = "Kugane Castle",
                            PvEContentTypeId = 1,
                            iLevel = 280
                        },
                        new
                        {
                            Id = 57,
                            Level = 70,
                            Name = "The Temple of the Fist",
                            PvEContentTypeId = 1,
                            iLevel = 280
                        },
                        new
                        {
                            Id = 58,
                            Level = 70,
                            Name = "The Drowned City of Skalla",
                            PvEContentTypeId = 1,
                            iLevel = 300
                        },
                        new
                        {
                            Id = 59,
                            Level = 70,
                            Name = "Hells' Lid",
                            PvEContentTypeId = 1,
                            iLevel = 310
                        },
                        new
                        {
                            Id = 60,
                            Level = 70,
                            Name = "The Fractal Continuum (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 310
                        },
                        new
                        {
                            Id = 61,
                            Level = 70,
                            Name = "The Swallow's Compass",
                            PvEContentTypeId = 1,
                            iLevel = 330
                        },
                        new
                        {
                            Id = 62,
                            Level = 70,
                            Name = "Saint Mocianne's Arboretum (Hard)",
                            PvEContentTypeId = 1,
                            iLevel = 340
                        },
                        new
                        {
                            Id = 63,
                            Level = 70,
                            Name = "The Burn",
                            PvEContentTypeId = 1,
                            iLevel = 340
                        },
                        new
                        {
                            Id = 64,
                            Level = 70,
                            Name = "The Ghimlyt Dark",
                            PvEContentTypeId = 1,
                            iLevel = 360
                        },
                        new
                        {
                            Id = 65,
                            Level = 71,
                            Name = "Holminster Switch",
                            PvEContentTypeId = 1,
                            iLevel = 370
                        },
                        new
                        {
                            Id = 66,
                            Level = 73,
                            Name = "Dohn Mheg",
                            PvEContentTypeId = 1,
                            iLevel = 375
                        },
                        new
                        {
                            Id = 67,
                            Level = 75,
                            Name = "The Qitana Ravel",
                            PvEContentTypeId = 1,
                            iLevel = 380
                        },
                        new
                        {
                            Id = 68,
                            Level = 77,
                            Name = "Malikah's Well",
                            PvEContentTypeId = 1,
                            iLevel = 385
                        },
                        new
                        {
                            Id = 69,
                            Level = 79,
                            Name = "Mt. Gulg",
                            PvEContentTypeId = 1,
                            iLevel = 390
                        },
                        new
                        {
                            Id = 70,
                            Level = 80,
                            Name = "Amaurot",
                            PvEContentTypeId = 1,
                            iLevel = 410
                        },
                        new
                        {
                            Id = 71,
                            Level = 80,
                            Name = "The Twinning",
                            PvEContentTypeId = 1,
                            iLevel = 410
                        },
                        new
                        {
                            Id = 72,
                            Level = 80,
                            Name = "Akadaemia Anyder",
                            PvEContentTypeId = 1,
                            iLevel = 410
                        },
                        new
                        {
                            Id = 73,
                            Level = 80,
                            Name = "The Grand Cosmos",
                            PvEContentTypeId = 1,
                            iLevel = 430
                        },
                        new
                        {
                            Id = 74,
                            Level = 20,
                            Name = "The Bowl of Embers",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 75,
                            Level = 34,
                            Name = "The Navel",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 76,
                            Level = 44,
                            Name = "The Howling Eye",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 77,
                            Level = 49,
                            Name = "Cape Westwind",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 78,
                            Level = 50,
                            Name = "The Chrysalis",
                            PvEContentTypeId = 3,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 79,
                            Level = 50,
                            Name = "The Steps of Faith",
                            PvEContentTypeId = 3,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 80,
                            Level = 50,
                            Name = "A Relic Reborn: The Chimera",
                            PvEContentTypeId = 3,
                            iLevel = 52
                        },
                        new
                        {
                            Id = 81,
                            Level = 50,
                            Name = "A Relic Reborn: The Hydra",
                            PvEContentTypeId = 3,
                            iLevel = 52
                        },
                        new
                        {
                            Id = 82,
                            Level = 50,
                            Name = "Battle on the Big Bridge",
                            PvEContentTypeId = 3,
                            iLevel = 50
                        },
                        new
                        {
                            Id = 83,
                            Level = 50,
                            Name = "The Dragon's Neck",
                            PvEContentTypeId = 3,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 84,
                            Level = 50,
                            Name = "Battle in the Big Keep",
                            PvEContentTypeId = 3,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 85,
                            Level = 50,
                            Name = "The Bowl of Embers (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 49
                        },
                        new
                        {
                            Id = 86,
                            Level = 50,
                            Name = "The Howling Eye (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 52
                        },
                        new
                        {
                            Id = 87,
                            Level = 50,
                            Name = "The Navel (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 57
                        },
                        new
                        {
                            Id = 88,
                            Level = 50,
                            Name = "Thornmarch (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 54
                        },
                        new
                        {
                            Id = 89,
                            Level = 50,
                            Name = "The Whorleater (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 60
                        },
                        new
                        {
                            Id = 90,
                            Level = 50,
                            Name = "The Striking Tree (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 65
                        },
                        new
                        {
                            Id = 91,
                            Level = 50,
                            Name = "Akh Afah Amphitheatre (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 92,
                            Level = 50,
                            Name = "Urth's Fount",
                            PvEContentTypeId = 3,
                            iLevel = 95
                        },
                        new
                        {
                            Id = 93,
                            Level = 50,
                            Name = "The Minstrel's Ballad: Ultima's Bane",
                            PvEContentTypeId = 3,
                            iLevel = 61
                        },
                        new
                        {
                            Id = 94,
                            Level = 50,
                            Name = "The Howling Eye (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 65
                        },
                        new
                        {
                            Id = 95,
                            Level = 50,
                            Name = "The Navel (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 67
                        },
                        new
                        {
                            Id = 96,
                            Level = 50,
                            Name = "The Bowl of Embers (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 67
                        },
                        new
                        {
                            Id = 97,
                            Level = 50,
                            Name = "Thornmarch (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 98,
                            Level = 50,
                            Name = "The Whorleater (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 80
                        },
                        new
                        {
                            Id = 99,
                            Level = 50,
                            Name = "The Striking Tree (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 85
                        },
                        new
                        {
                            Id = 100,
                            Level = 50,
                            Name = "Akh Afah Amphitheatre (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 95
                        },
                        new
                        {
                            Id = 101,
                            Level = 53,
                            Name = "Thok ast Thok (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 102,
                            Level = 57,
                            Name = "The Limitless Blue (Hard)",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 103,
                            Level = 60,
                            Name = "The Singularity Reactor",
                            PvEContentTypeId = 3,
                            iLevel = 142
                        },
                        new
                        {
                            Id = 104,
                            Level = 60,
                            Name = "The Final Steps of Faith",
                            PvEContentTypeId = 3,
                            iLevel = 205
                        },
                        new
                        {
                            Id = 105,
                            Level = 60,
                            Name = "Containment Bay S1T7",
                            PvEContentTypeId = 3,
                            iLevel = 190
                        },
                        new
                        {
                            Id = 106,
                            Level = 60,
                            Name = "Containment Bay P1T6",
                            PvEContentTypeId = 3,
                            iLevel = 220
                        },
                        new
                        {
                            Id = 107,
                            Level = 60,
                            Name = "Containment Bay Z1T9",
                            PvEContentTypeId = 3,
                            iLevel = 235
                        },
                        new
                        {
                            Id = 108,
                            Level = 60,
                            Name = "The Limitless Blue (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 165
                        },
                        new
                        {
                            Id = 109,
                            Level = 60,
                            Name = "Thok ast Thok (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 175
                        },
                        new
                        {
                            Id = 110,
                            Level = 60,
                            Name = "The Minstrel's Ballad: Thordan's Reign",
                            PvEContentTypeId = 3,
                            iLevel = 190
                        },
                        new
                        {
                            Id = 111,
                            Level = 60,
                            Name = "The Minstrel's Ballad: Nidhogg's Rage",
                            PvEContentTypeId = 3,
                            iLevel = 220
                        },
                        new
                        {
                            Id = 112,
                            Level = 60,
                            Name = "Containment Bay S1T7 (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 205
                        },
                        new
                        {
                            Id = 113,
                            Level = 60,
                            Name = "Containment Bay P1T6 (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 235
                        },
                        new
                        {
                            Id = 114,
                            Level = 60,
                            Name = "Containment Bay Z1T9 (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 250
                        },
                        new
                        {
                            Id = 115,
                            Level = 63,
                            Name = "The Pool of Tribute",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 116,
                            Level = 67,
                            Name = "Emanation",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 117,
                            Level = 70,
                            Name = "The Royal Menagerie",
                            PvEContentTypeId = 3,
                            iLevel = 280
                        },
                        new
                        {
                            Id = 118,
                            Level = 70,
                            Name = "The Jade Stoa",
                            PvEContentTypeId = 3,
                            iLevel = 325
                        },
                        new
                        {
                            Id = 119,
                            Level = 70,
                            Name = "Castrum Fluminis",
                            PvEContentTypeId = 3,
                            iLevel = 335
                        },
                        new
                        {
                            Id = 120,
                            Level = 70,
                            Name = "The Great Hunt",
                            PvEContentTypeId = 3,
                            iLevel = 320
                        },
                        new
                        {
                            Id = 121,
                            Level = 70,
                            Name = "Hells' Kier",
                            PvEContentTypeId = 3,
                            iLevel = 355
                        },
                        new
                        {
                            Id = 122,
                            Level = 70,
                            Name = "The Wreath of Snakes",
                            PvEContentTypeId = 3,
                            iLevel = 365
                        },
                        new
                        {
                            Id = 123,
                            Level = 70,
                            Name = "Kugane Ohashi",
                            PvEContentTypeId = 3,
                            iLevel = 365
                        },
                        new
                        {
                            Id = 124,
                            Level = 70,
                            Name = "The Pool of Tribute (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 300
                        },
                        new
                        {
                            Id = 125,
                            Level = 70,
                            Name = "Emanation (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 300
                        },
                        new
                        {
                            Id = 126,
                            Level = 70,
                            Name = "The Minstrel's Ballad: Shinryu's Domain",
                            PvEContentTypeId = 3,
                            iLevel = 320
                        },
                        new
                        {
                            Id = 127,
                            Level = 70,
                            Name = "The Jade Stoa (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 340
                        },
                        new
                        {
                            Id = 128,
                            Level = 70,
                            Name = "The Minstrel's Ballad: Tsukuyomi's Pain",
                            PvEContentTypeId = 3,
                            iLevel = 350
                        },
                        new
                        {
                            Id = 129,
                            Level = 70,
                            Name = "The Great Hunt (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 350
                        },
                        new
                        {
                            Id = 130,
                            Level = 70,
                            Name = "Hells' Kier (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 370
                        },
                        new
                        {
                            Id = 131,
                            Level = 70,
                            Name = "The Wreath of Snakes (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 380
                        },
                        new
                        {
                            Id = 132,
                            Level = 73,
                            Name = "The Dancing Plague",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 133,
                            Level = 79,
                            Name = "The Crown of the Immaculate",
                            PvEContentTypeId = 3,
                            iLevel = 0
                        },
                        new
                        {
                            Id = 134,
                            Level = 80,
                            Name = "The Dying Gasp",
                            PvEContentTypeId = 3,
                            iLevel = 410
                        },
                        new
                        {
                            Id = 135,
                            Level = 80,
                            Name = "The Dancing Plague (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 430
                        },
                        new
                        {
                            Id = 136,
                            Level = 80,
                            Name = "The Crown of the Immaculate (Extreme)",
                            PvEContentTypeId = 3,
                            iLevel = 430
                        },
                        new
                        {
                            Id = 137,
                            Level = 80,
                            Name = "The Minstrel's Ballad: Hades' Elegy",
                            PvEContentTypeId = 3,
                            iLevel = 450
                        },
                        new
                        {
                            Id = 138,
                            Level = 50,
                            Name = "The Binding Coil of Bahamut",
                            PvEContentTypeId = 2,
                            iLevel = 70
                        },
                        new
                        {
                            Id = 139,
                            Level = 50,
                            Name = "The Second Coil of Bahamut",
                            PvEContentTypeId = 2,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 140,
                            Level = 50,
                            Name = "The Second Coil of Bahamu (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 141,
                            Level = 50,
                            Name = "The Final Coil of Bahamut",
                            PvEContentTypeId = 2,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 142,
                            Level = 60,
                            Name = "Alexander: Gordias",
                            PvEContentTypeId = 2,
                            iLevel = 170
                        },
                        new
                        {
                            Id = 143,
                            Level = 60,
                            Name = "Alexander: Gordia (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 190
                        },
                        new
                        {
                            Id = 144,
                            Level = 60,
                            Name = "Alexander: Midas",
                            PvEContentTypeId = 2,
                            iLevel = 200
                        },
                        new
                        {
                            Id = 145,
                            Level = 60,
                            Name = "Alexander: Midas (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 215
                        },
                        new
                        {
                            Id = 146,
                            Level = 60,
                            Name = "Alexander: The Creator",
                            PvEContentTypeId = 2,
                            iLevel = 230
                        },
                        new
                        {
                            Id = 147,
                            Level = 60,
                            Name = "Alexander: The Creator (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 245
                        },
                        new
                        {
                            Id = 148,
                            Level = 70,
                            Name = "Omega: Deltascape",
                            PvEContentTypeId = 2,
                            iLevel = 295
                        },
                        new
                        {
                            Id = 149,
                            Level = 70,
                            Name = "Omega: Deltascape (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 310
                        },
                        new
                        {
                            Id = 150,
                            Level = 70,
                            Name = "The Unending Coil of Bahamut (Ultimate)",
                            PvEContentTypeId = 2,
                            iLevel = 340
                        },
                        new
                        {
                            Id = 151,
                            Level = 70,
                            Name = "Omega: Sigmascape",
                            PvEContentTypeId = 2,
                            iLevel = 325
                        },
                        new
                        {
                            Id = 152,
                            Level = 70,
                            Name = "Omega: Sigmascape (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 340
                        },
                        new
                        {
                            Id = 153,
                            Level = 70,
                            Name = "The Minstrel's Ballad: The Weapon's Refrain (Ultimate)",
                            PvEContentTypeId = 2,
                            iLevel = 370
                        },
                        new
                        {
                            Id = 154,
                            Level = 70,
                            Name = "Omega: Alphascape",
                            PvEContentTypeId = 2,
                            iLevel = 355
                        },
                        new
                        {
                            Id = 155,
                            Level = 70,
                            Name = "Omega: Alphascape (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 370
                        },
                        new
                        {
                            Id = 156,
                            Level = 80,
                            Name = "Eden's Gate",
                            PvEContentTypeId = 2,
                            iLevel = 425
                        },
                        new
                        {
                            Id = 157,
                            Level = 80,
                            Name = "Eden's Gate (Savage)",
                            PvEContentTypeId = 2,
                            iLevel = 440
                        },
                        new
                        {
                            Id = 158,
                            Level = 80,
                            Name = "The Epic of Alexander (Ultimate)",
                            PvEContentTypeId = 2,
                            iLevel = 470
                        },
                        new
                        {
                            Id = 159,
                            Level = 50,
                            Name = "Labyrinth of the Ancients",
                            PvEContentTypeId = 4,
                            iLevel = 50
                        },
                        new
                        {
                            Id = 160,
                            Level = 50,
                            Name = "Syrcus Tower",
                            PvEContentTypeId = 4,
                            iLevel = 70
                        },
                        new
                        {
                            Id = 161,
                            Level = 50,
                            Name = "The World of Darkness",
                            PvEContentTypeId = 4,
                            iLevel = 90
                        },
                        new
                        {
                            Id = 162,
                            Level = 60,
                            Name = "The Void Ark",
                            PvEContentTypeId = 4,
                            iLevel = 175
                        },
                        new
                        {
                            Id = 163,
                            Level = 60,
                            Name = "The Weeping City of Mhach",
                            PvEContentTypeId = 4,
                            iLevel = 205
                        },
                        new
                        {
                            Id = 164,
                            Level = 60,
                            Name = "Dun Scaith",
                            PvEContentTypeId = 4,
                            iLevel = 235
                        },
                        new
                        {
                            Id = 165,
                            Level = 70,
                            Name = "The Royal City of Rabanastre",
                            PvEContentTypeId = 4,
                            iLevel = 305
                        },
                        new
                        {
                            Id = 166,
                            Level = 70,
                            Name = "The Ridorana Lighthouse",
                            PvEContentTypeId = 4,
                            iLevel = 335
                        },
                        new
                        {
                            Id = 167,
                            Level = 70,
                            Name = "The Orbonne Monastery",
                            PvEContentTypeId = 4,
                            iLevel = 365
                        },
                        new
                        {
                            Id = 168,
                            Level = 80,
                            Name = "The Copied Factory",
                            PvEContentTypeId = 4,
                            iLevel = 435
                        });
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.PvEContentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PvEContentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dungeon"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Raid"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trial"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Alliance Raid"
                        });
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "La Noscea"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Black Shroud"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thanalan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mor Dhona"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Coerthas"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Abalathia's Spine"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dravania"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gyr Abania"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Othard"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Hingashi"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Norvrandt"
                        });
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.SightseeingEmote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("SightseeingEmote");
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<int>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Zone");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Limsa Lominsa Upper Decks",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Limsa Lominsa Lower Decks",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lower La Noscea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Middle La Noscea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Eastern la Noscea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Western la Noscea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Outer La Noscea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Upper La Noscea",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "The Mist",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Wolves' Den Pier",
                            RegionId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Ul'dah - Steps of Nald",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ul'dah - Steps of Thal",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 13,
                            Name = "Central Thanalan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 14,
                            Name = "Western Thanalan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 15,
                            Name = "Eastern Thanalan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Southern Thanalan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Northern Thanalan",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "The Goblet",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Old Gridania",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "New Gridania",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Central Shroud",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "North Shroud",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "East Shroud",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 24,
                            Name = "South Shroud",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 25,
                            Name = "Lavender Beds",
                            RegionId = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "Mor Dhona",
                            RegionId = 4
                        },
                        new
                        {
                            Id = 27,
                            Name = "Foundation",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 28,
                            Name = "The Pillars",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 29,
                            Name = "Coerthas Central Highlands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 30,
                            Name = "Coerthas Western Highlands",
                            RegionId = 5
                        },
                        new
                        {
                            Id = 31,
                            Name = "The Sea of Clouds",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 32,
                            Name = "Azys Lla",
                            RegionId = 6
                        },
                        new
                        {
                            Id = 33,
                            Name = "Idyllshire",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 34,
                            Name = "Dravanian Forelands",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 35,
                            Name = "Dravanian Hinterlands",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 36,
                            Name = "The Churning Mists",
                            RegionId = 7
                        },
                        new
                        {
                            Id = 37,
                            Name = "Rhalgr's Reach",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 38,
                            Name = "The Fringes",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 39,
                            Name = "The Lochs",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 40,
                            Name = "The Peaks",
                            RegionId = 8
                        },
                        new
                        {
                            Id = 41,
                            Name = "The Azim Steppe",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 42,
                            Name = "The Ruby Sea",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 43,
                            Name = "Yanxia",
                            RegionId = 9
                        },
                        new
                        {
                            Id = 44,
                            Name = "Kugane",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 45,
                            Name = "Shirogane",
                            RegionId = 10
                        },
                        new
                        {
                            Id = 46,
                            Name = "The Crystarium",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 47,
                            Name = "Eulmore - The Canopy",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 48,
                            Name = "Eulmore - The Understory",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 49,
                            Name = "Eulmore - The Buttress",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 50,
                            Name = "Lakeland",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 51,
                            Name = "Kholusia",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 52,
                            Name = "Amh Araeng",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 53,
                            Name = "Il Mheg",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 54,
                            Name = "The Rak'tika Greatwood",
                            RegionId = 11
                        },
                        new
                        {
                            Id = 55,
                            Name = "The Tempest",
                            RegionId = 11
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("XIVChecklist.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("XIVChecklist.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("XIVChecklist.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("XIVChecklist.Entities.AppUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Location", b =>
                {
                    b.HasOne("XIVChecklist.Entities.Common.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("XIVChecklist.Entities.Common.Zone", b =>
                {
                    b.HasOne("XIVChecklist.Entities.Common.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
