using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace XIVChecklist.Data.Migrations
{
    public partial class CollectionTasks : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable("CollectionTask");

            migrationBuilder.CreateTable(
                name: "CollectionTask",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    CategoryId = table.Column<int>(nullable: false),
                    Name = table.Column<string>(nullable: true),
                    Method = table.Column<string>(nullable: true),
                    CollectionTypeId = table.Column<int>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CollectionTask", x => x.Id);
                    table.ForeignKey(
                        name: "FK_CollectionTask_Category",
                        column: x => x.CategoryId,
                        principalTable: "Category",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_CollectionTask_CollectionType",
                        column: x => x.CollectionTypeId,
                        principalTable: "CollectionType",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "CollectionTask",
                columns: new[] { "Id", "CategoryId", "CollectionTypeId", "Method", "Name" },
                values: new object[,]
                {
                    { 1, 25, 1, "Purchase from Modern Aesthetics Saleswoman for 14 MPG", "Adventure" },
                    { 458, 25, 4, "Possible Wondrous Tails reward.", "Wind-up Khloe" },
                    { 459, 25, 4, "Bought from Kobold Vendor for 25,000 Gil.", "Wind-up Kobold" },
                    { 460, 25, 4, "Bought from Kobold Vendor for 25,000 Gil.", "Wind-up Kobolder" },
                    { 461, 25, 4, "Kojiin Beast Tribe Reward. Costs 5 Kojin Sango from Shikitahe.", "Wind-up Kojin" },
                    { 462, 25, 4, "Acquired from The Rising (2016). MogStation: 5 USD / 3.5 EUR", "Wind-up Krile" },
                    { 463, 25, 4, "Crafted by level 70★ Weaver.", "Wind-up Lakshmi" },
                    { 464, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Wind-up Leader" },
                    { 465, 25, 4, "Crafted by level 60★ Weaver.", "Wind-up Leviathan" },
                    { 466, 25, 4, "Complete the Out of a Bind I achievement by completing The Final Coil of Bahamut.", "Wind-Up Louisoix" },
                    { 467, 25, 4, "Fan Fest 2016 in Tokyo Event/Live Stream Ticket", "Wind-up Lulu" },
                    { 468, 25, 4, "Acquired from The Rising (2017). MogStation: 5 USD / 3.5 EUR", "Wind-up Lyse" },
                    { 469, 25, 4, "Level 70 ★★ Weaver recipe.", "Wind-up Magnai" },
                    { 470, 25, 4, "Potential reward from the Hidden Canals of Uznair", "Wind-up Matanga" },
                    { 471, 25, 4, "Purchased from Estrild in Kugane with 800 Centurio Seals.", "Wind-up Meateater" },
                    { 472, 25, 4, "Acquired from The Rising (2014). MogStation: 5 USD / 3.5 EUR", "Wind-up Minfilia" },
                    { 473, 25, 4, "Rarely from Short Serket 2 in Eureka Anemos.", "Wind-up Mithra" },
                    { 474, 25, 4, "Complete Level 60 Main Scenario Quest An Ending to Mark a New Beginning.", "Wind-up Moenbryda" },
                    { 457, 25, 4, "Guaranteed drop from Sigmascape V4.0 and Sigmascape V4.0 (Savage).", "Wind-up Kefka" },
                    { 456, 25, 4, "Heavensward Collector's Edition", "Wind-up Kain" },
                    { 455, 25, 4, "Traded from Eschina for 5 Ixion Horns", "Wind-up Ixion" },
                    { 454, 25, 4, "Purchased from Ixali Vendor for 25,000 gil", "Wind-up Ixal" },
                    { 436, 25, 4, "Purchased from Amalj'aa Vendor for 25,000 gil ", "Wind-up Founder" },
                    { 437, 25, 4, "Purchase Collector's Edition of Shadowbringers", "Wind-up Fran" },
                    { 438, 25, 4, "Drops from Dungeons of Lyhe Ghiah", "Wind-up Fuath" },
                    { 439, 25, 4, "Complete the Level 80 Main Scenario Quest Shadowbringers.", "Wind-up G'raha Tia" },
                    { 440, 25, 4, "Crafted by Level 60★ Weaver", "Wind-up Garuda" },
                    { 441, 25, 4, "Complete the Level 50 Hildibrand questline Her Last Vow.", "Wind-up Gentleman" },
                    { 442, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Wind-up Gilgamesh" },
                    { 443, 25, 4, "30,000 gil and Rank 7 (Sworn Reputation) from Vath Stickpeddler.", "Wind-up Gnath" },
                    { 475, 25, 4, "Final Fantasy XIV: A Realm Reborn Collector's Edition", "Wind-up Moogle" },
                    { 444, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Wind-up Goblin" },
                    { 446, 25, 4, "Purchased from Luna Vanu for 30,000 gil ", "Wind-up Gundu Warrior" },
                    { 447, 25, 4, "Complete the Level 60 Main Scenario Quest As Goes Light, So Goes Darkness.", "Wind-up Haurchefant" },
                    { 448, 25, 4, "Potential reward from Wondrous Tails", "Wind-up Hien" },
                    { 449, 25, 4, "Highland Exploration XXV Miner Retainer Venture or Quick Exploration", "Wind-up Hobgoblin" },
                    { 450, 25, 4, "FINAL FANTASY XIV: HEAVENSWARD - The Scars of War Art Book", "Wind-up Hraesvelgr" },
                    { 451, 25, 4, "Acquired from The Rising (2015). MogStation: 5 USD / 3.5 EUR", "Wind-up Iceheart" },
                    { 452, 25, 4, "Crafted by Level 60★ Weaver.", "Wind-up Ifrit" },
                    { 453, 25, 4, "Crafted by Level 60★ Weaver.", "Wind-up Illuminatus" },
                    { 445, 25, 4, "Acquired from The Rising (2017). MogStation: 5 USD / 3.5 EUR", "Wind-up Gosetsu" },
                    { 435, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Wind-up Firion" },
                    { 476, 25, 4, "Trade 1 Hi-Elixir to the Magic Pot on The Isles of Umbra.", "Wind-up Moon" },
                    { 478, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Wind-up Nanamo" },
                    { 501, 25, 4, "Drops at the end of Dun Scaith", "Wind-up Scathach" },
                    { 502, 25, 4, "Purchased from Sahagin Vendor for 25,000 gil ", "Wind-up Sea Devil" },
                    { 503, 25, 4, "Complete the FFXI Cross-over Event quest Burgeoning Dread. MogStation: 5 USD / 3.5 EUR", "Wind-up Shantotto" },
                    { 504, 25, 4, "Level 70 ★★ Weaver recipe.", "Wind-up Shinryu" },
                    { 505, 25, 4, "Crafted by level 60★ Weaver.", "Wind-up Shiva" },
                    { 506, 25, 4, "Grand Company's Hunt Billmaster for 500 Allied Seals.", "Wind-up Succubus" },
                    { 507, 25, 4, "Give an Elixir to the Magic Pot at The Ship Graveyard.", "Wind-up Sun" },
                    { 508, 25, 4, "Level 70 ★ Weaver recipe.", "Wind-up Susano" },
                    { 509, 25, 4, "From the SHADOWBRINGERS: FINAL FANTASY XIV Original Soundtrack.", "Wind-up Suzaku" },
                    { 510, 25, 4, "Purchased from Sylph Vendor for 25,000 gil", "Wind-up Sylph" },
                    { 511, 25, 4, "From Lockboxes in Eureka: Pagos", "Wind-up Tarutaru" },
                    { 512, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Wind-up Tataru" },
                    { 513, 25, 4, "Acquired from The Rising (2014). MogStation: 5 USD / 3.5 EUR", "Wind-up Thancred" },
                    { 514, 25, 4, "MogStation: 6.99 USD", "Wind-up Tifa" },
                    { 515, 25, 4, "Crafted by level 60★ Weaver.", "Wind-up Titan" },
                    { 516, 25, 4, "Boarskin Treasure Hunt, The Aquapolis, or Palace of the Dead Bronze-trimmed Sacks.", "Wind-up Tonberry" },
                    { 517, 25, 4, "From the STORMBLOOD: FINAL FANTASY XIV Original Soundtrack.", "Wind-up Tsukuyomi" },
                    { 500, 25, 4, "3 Gelmorran Potsherds from E-Una-Kotor at Quarrymill", "Wind-up Sasquatch" },
                    { 499, 25, 4, "Bought from Sahagin Vendor for 25,000 Gil.", "Wind-up Sahagin" },
                    { 498, 25, 4, "Level 70 ★★ Weaver recipe.", "Wind-up Sadu" },
                    { 497, 25, 4, "Fan Fest 2016 in Las Vegas Event/Live Stream Ticket", "Wind-up Rikku" },
                    { 479, 25, 4, "Purchased from Gold Saucer Attendant for 30,000 MGP", "Wind-up Nero tol Scaeva" },
                    { 480, 25, 4, "The Far Edge of Fate: Final Fantasy XIV Original Soundtrack", "Wind-up Nidhogg" },
                    { 481, 25, 4, "800x Sacks of Nuts", "Wind-up Nu Mou" },
                    { 482, 25, 4, "Obtained from Jonathas in Old Gridania ( X:10.6 Y:6.3) for 2 Achievement Certificates.", "Wind-up Odin" },
                    { 483, 25, 4, "30,000 Gil from Mogmul Mogbelly at Allied rank", "Wind-up Ohl Deeh" },
                    { 484, 25, 4, "Reward for Wondrous Tales", "Wind-up Omega-F" },
                    { 485, 25, 4, "Reward for Wondrous Tales", "Wind-up Omega-M" },
                    { 486, 25, 4, "Found in rare extra chest after final boss of Syrcus Tower.", "Wind-up Onion Knight" },
                    { 477, 25, 4, "Rarely from Gazelleskin Treasure Maps.", "Wind-up Namazu" },
                    { 487, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Wind-up Papalymo" },
                    { 489, 25, 4, "7x Ananta Dreamstaff from the Ananta Reputation Vendor", "Wind-up Qalyana" },
                    { 490, 25, 4, "Crafted by Level 50 Weaver.", "Wind-up Qiqirn" },
                    { 491, 25, 4, "Crafted by level 60★ Weaver.", "Wind-up Ramuh" },
                    { 492, 25, 4, "Drops from the Osbonne Monastery", "Wind-up Ramza" },
                    { 493, 25, 4, "Crafted by level 60★ Weaver.", "Wind-up Ravana" },
                    { 494, 25, 4, "Preordering Stormblood", "Wind-up Red Mage" },
                    { 495, 25, 4, "Kojiin Beast Tribe Reward. Costs 5 Kojin Sango from Shikitahe.", "Wind-up Redback" },
                    { 496, 25, 4, "HEAVENSWARD | The Art of Ishgard - Stone and Steel Art Book", "Wind-up Relm" },
                    { 488, 25, 4, "8x Fae Fancy from the Pixie Reputation Vendor", "Wind-up Pixie" },
                    { 434, 25, 4, "Occasional drop from Wine and Honey FATE in Eureka Anemos", "Wind-up Fafnir" },
                    { 433, 25, 4, "Found in chest after final boss of Deltascape V4.0.", "Wind-up Exdeath" },
                    { 432, 25, 4, "Randomly the 2-line reward of Wondrous Tails.", "Wind-up Estinien" },
                    { 371, 25, 4, "Randomly drops from chest in Copperbell Mines (Hard).", "Slime Puddle" },
                    { 372, 25, 4, "Complete the FATE: It's Not Lupus with a Gold Medal rating", "Smallshell" },
                    { 373, 25, 4, "Final Fantasy XIV: Heavensward Soundtrack", "Spoony Bard" },
                    { 374, 25, 4, "Crafted by Level 60★ Armorer.", "Steam-powered Gobwalker G-VII" },
                    { 375, 25, 4, "Purchased for 20,000 Storm Seals.", "Storm Hatchling" },
                    { 376, 25, 4, "Purchased from Itinerant Moogle for 140 gil", "Taoist Moogle" },
                    { 377, 25, 4, "Acquired from Heavensturn (2015). MogStation: 5 USD / 3.5 EUR", "Tender Lamb" },
                    { 378, 25, 4, "Field Exploration XXII Combat Retainer Venture or Quick Exploration", "Tengu Doll" },
                    { 379, 25, 4, "The Hidden Canals of Uznair", "The Gold Whisker" },
                    { 380, 25, 4, "Complete Level 70 Side Quest Protectors of the Wood", "The Great Serpent of Ronka" },
                    { 381, 25, 4, "Occasional drop from The Shadow over Anemos in Eureka Anemos", "The Prince of Anemos" },
                    { 382, 25, 4, "Rarely drops from chest in Sastasha (Hard).", "Tight-beaked Parrot" },
                    { 383, 25, 4, "Purchased from Fathard in Eulmore Aetheryte Plaza for 6 Archaeotania's Horn", "Tinker's Bell" },
                    { 384, 25, 4, "Rare reward from Treasure Hunting", "Tiny Bulb" },
                    { 385, 25, 4, "Dohn Mheg", "Tiny Echevore" },
                    { 386, 25, 4, "From Chachamun for 2400 gil after successfully completing Attack on Highbridge: Act II", "Tiny Rat" },
                    { 387, 25, 4, "Field Exploration XIV, XV, and XIX Combat Retainer Venture", "Tiny Tapir" },
                    { 370, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Shogunyan" },
                    { 369, 25, 4, "Dropped from Amaurot", "Shoebill" },
                    { 368, 25, 4, "Subaquatic Voyages - The Central Charnel Trench, The Southern Charnel Trench", "Sharksucker-class Insubmersible" },
                    { 367, 25, 4, "Complete the A Load of Verminion II Achievement", "Shalloweye" },
                    { 349, 25, 4, "Crafted by Level 50★★★ Weaver.", "Plush Cushion" },
                    { 350, 25, 4, "Found in chest after final boss of The Copied City", "Pod 054" },
                    { 351, 25, 4, "Found in chest after final boss of The Copied City", "Pod 316" },
                    { 352, 25, 4, "5x Scales from the Rathalos Scale Exchange shop", "Poogie" },
                    { 353, 25, 4, "Complete the Level 60 Main Scenario Quest The Word of the Mother.", "Poro Roggo" },
                    { 354, 25, 4, "Before the Fall: Final Fantasy XIV Original Soundtrack", "The Primogs" },
                    { 355, 25, 4, "Complete the Leaving a Good Impression II Achievement", "Princely Hatchling" },
                    { 356, 25, 4, "Level 70 ★★ Blacksmith recipe.", "Private Moai" },
                    { 388, 25, 4, "Spearfishing in the Ruby Sea", "Tiny Tatsunoko" },
                    { 357, 25, 4, "Complete the FATE: The Eyes Have It (FATE) with a Gold Medal rating", "Pudgy Puk" },
                    { 359, 25, 4, "Acquired from the All Saints' Wake (2015). MogStation: 5 USD / 3.5 EUR", "Pumpkin Butler" },
                    { 360, 25, 4, "Rare drop after completing Bardam's Mettle.", "Road Sparrow" },
                    { 361, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Robonyan F-type" },
                    { 362, 25, 4, "Dropped in The Drowned City of Skalla", "Salt & Pepper Seal" },
                    { 363, 25, 4, "Level 70 ★★★ Weaver recipe.", "Scarlet Peacock" },
                    { 364, 25, 4, "Level 70 ★★★★ Weaver recipe.", "Seitei" },
                    { 365, 25, 4, "Purchased for 20,000 Serpent Seals.", "Serpent Hatchling" },
                    { 366, 25, 4, "Rarely found in chest after final boss of Xelphatol.", "Shaggy Shoat" },
                    { 358, 25, 4, "Found in World of Darkness.", "Puff of Darkness" },
                    { 389, 25, 4, "Use Northern Krill and fish from the The Salt Strand in Lower La Noscea.", "Tiny Tortoise" },
                    { 390, 25, 4, "Intercrossing: Dzemael Tomato w Mandrake OR Krakka Root w Broombush OR Jute w Krakka Root", "Tomato King" },
                    { 391, 25, 4, "Purchased for 800 Centurio Seals from Estril in Kugane", "Tora-jiro" },
                    { 414, 25, 4, "Crafted by Level 60★ Weaver.", "Wind-up Bismarck" },
                    { 415, 25, 4, "Complete the event quest Breaking Brick Mountains", "Wind-up Brickman" },
                    { 416, 25, 4, "Found in chest after final boss of The Weeping City of Mhach.", "Wind-up Calofisteri" },
                    { 417, 25, 4, "Purchased from Storm Sergeant for 15,000 Wolf Marks in Wolves' Den Pier.", "Wind-up Cheerleader" },
                    { 418, 25, 4, "Crafted by Level 70★ Weaver.", "Wind-up Chimera" },
                    { 419, 25, 4, "Complete the Level 57 Main Scenario Quest A Difference of Opinion.", "Wind-up Cid" },
                    { 420, 25, 4, "In Adventurers We Trust Seasonal Quest reward (The Rising (2018) anniversary event.)", "Wind-up Cirina" },
                    { 421, 25, 4, "Mog Station (once the 2019 Japan Fan Festival goes live)", "Wind-Up Cloud" },
                    { 413, 25, 4, "Purchase Collector's Edition of Stormblood", "Wind-up Bartz" },
                    { 422, 25, 4, "Obtained from Jonathas in Old Gridania ( X:10.6 Y:6.3) for 2 Achievement Certificates.", "Wind-up Cursor" },
                    { 424, 25, 4, "Delivery Moogle Plush", "Wind-up Deliver Moogle" },
                    { 425, 25, 4, "Purchased from Ixali Vendor for 25,000 gil in North Shroud", "Wind-up Dezul Qualan" },
                    { 426, 25, 4, "Purchased from Mogmul Mogbelly for 30,000 gil at Sworn (or higher) reputation", "Wind-up Dragonet" },
                    { 427, 25, 4, "Crafted by Level 50 Armorer.", "Wind-up Dullahan" },
                    { 428, 25, 4, "Found in chest after final boss of The Void Ark.", "Wind-up Echidna" },
                    { 429, 25, 4, "From Iron Trimmed Sacks found in Palace of the Dead.", "Wind-up Edda" },
                    { 430, 25, 4, "Acquired from the Little Ladies' Day. MogStation: 5 USD / 3.5 EUR", "Wind-up Edvya" },
                    { 431, 25, 4, "You Do Know Jack FATE in East Flamerock", "Wind-up Elvaan" },
                    { 423, 25, 4, "Obtained when you purchase the Before Meteor Blu-Ray Soundtrack from the Square Enix Store", "Wind-up Dalamud" },
                    { 518, 25, 4, "Obtained from The Dragon's Neck.", "Wind-up Ultros" },
                    { 412, 25, 4, "Final Fantasy XIV: A Realm Reborn Original Soundtrack", "Wind-up Bahamut" },
                    { 410, 25, 4, "7x Ananta Dreamstaff from the Ananta Reputation Vendor", "Wind-up Ananta" },
                    { 392, 25, 4, "Obtained from Alexander - The Soul of the Creator.", "Toy Alexander" },
                    { 393, 25, 4, "Purchased from Grand Company's Hunt vendor for 440 Allied Seals.", "Treasure Box" },
                    { 394, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "USApyon" },
                    { 395, 25, 4, "Found in chest after final boss of Neverreap.", "Ugly Duckling" },
                    { 396, 25, 4, "Found in chest after final boss of The Vault.", "Unicolt" },
                    { 397, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Venoct" },
                    { 398, 25, 4, "Purchased from Gold Saucer Attendant for 10,000 MGP", "Water Imp" },
                    { 399, 25, 4, "Purchased from Bango Zango in Limsa Lominsa, Roarich in Ul'dah, or Maisenta in New Gridania.", "Wayward Hatchling" },
                    { 411, 25, 4, "Complete the level 60 Main Scenario Quest Litany of Peace.", "Wind-up Aymeric" },
                    { 400, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Whisper" },
                    { 402, 25, 4, "Purchased from Auriana for 7 Allagan Tomestones of Soldiery", "Wide-eyed Fawn" },
                    { 403, 25, 4, "Mog Station (once the 2019 Japan Fan Festival goes live)", "Wind-up Aerith" },
                    { 404, 25, 4, "Obtain an airship pass (The Gridanian Envoy, The Ul'dahn Envoy, or The Lominsan Envoy.)", "Wind-up Airship" },
                    { 405, 25, 4, "Crafted by Level 50 Weaver.", "Wind-up Aldgoat" },
                    { 406, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Wind-up Alisae" },
                    { 407, 25, 4, "Post Alphascape 4.0 Quest", "Wind-up Alpha" },
                    { 408, 25, 4, "Complete the Level 51 Main Scenario Quest In Search of Iceheart.", "Wind-up Alphinaud" },
                    { 409, 25, 4, "Bought from Amalj'aa Vendor for 25,000 Gil.", "Wind-up Amalj'aa" },
                    { 401, 25, 4, "Rare drop from the final chest in Hells' Lid", "White Whittret" },
                    { 348, 25, 4, "Purchased from Gold Saucer Attendant for 30,000 MGP", "Piggy" },
                    { 519, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Wind-up Urianger" },
                    { 521, 25, 4, "Purchased from Sylph Vendor for 25,000 gil", "Wind-up Violet" },
                    { 631, 25, 5, "After completing the Main Scenario Quest Into the Aery.", "Manacutter" },
                    { 632, 25, 5, "8x Gold Chocobo Feathers, which are received from the Recruit a Friend Campaign.", "Managarm" },
                    { 633, 25, 5, "18x Ananta Dreamstaff from Madhura.", "Marid" },
                    { 634, 25, 5, "Obtained after defeating Ramuh in The Striking Tree (Extreme)", "Markab" },
                    { 635, 25, 5, "Feast Season 12 Reward", "Maxima Roader" },
                    { 636, 25, 5, "After completing the Main Scenario Quest Fetters of Lament.", "Midgardsormr" },
                    { 637, 25, 5, "20 Namazu Koban from Gyosho", "Mikoshi" },
                    { 638, 25, 5, "Raid reward for Alphascape V4.0 (Savage)", "Model O" },
                    { 639, 25, 5, "Awarded from the achievement True Blue", "Morbol" },
                    { 640, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Mystic Panda" },
                    { 641, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Nezha Chariot" },
                    { 642, 25, 5, "Summoned by Nightmare Whistle. Dropped by Garuda (Extreme), Titan (Extreme), and Ifrit (Extreme).", "Nightmare" },
                    { 643, 25, 5, "Limited time promotional event with 7-11 (JP), Amazon (US) and GamesMaster (EU)", "Original Fat Chocobo" },
                    { 644, 25, 5, "In The Feast Rewards (Season 4), Top 100 Party Ranking in a Datacenter.", "Pack Faehound" },
                    { 645, 25, 5, "In The Feast Rewards (Season 3), Top 100 Party Ranking in a Datacenter.", "Pack Hellhound" },
                    { 646, 25, 5, "Leaving a Better Impression II", "Parade Chocobo" },
                    { 647, 25, 5, "Purchased from Spoils Collector (The Pillars) for 99 Brass Sky Pirate Spoils.", "Pegasus" },
                    { 630, 25, 5, "The Feast Season 11 Reward", "Magna Roader" },
                    { 629, 25, 5, "Bought at PvP Merchant for 20,000 Wolf Marks.", "Magitek Sky Armor" },
                    { 628, 25, 5, "Dropped by Zenos yae Galvus in the dungeon Ala Mhigo (Dungeon).", "Magitek Predator" },
                    { 627, 25, 5, "6x Achievement Certificate from Jonathas in New Gridania.", "Magitek Death Claw" },
                    { 609, 25, 5, "Have all 4 Empyrean Accessories in your inventory and speak with Cast-off Confederate in Crick.", "Juedi" },
                    { 610, 25, 5, "Collect every Stormblood Extreme Primal Mount and complete A Lone Wolf No More sidequest.", "Kamuy of the Nine Tails" },
                    { 611, 25, 5, "Complete the A Legend for a Legend sidequest", "Kirin" },
                    { 612, 25, 5, "Obtain Rank 7 (Sworn) with Vath Beast Tribe.", "Kongamato" },
                    { 613, 25, 5, "Purchased in Gold Saucer for 750,000 MGP", "Korpokkur Kolossus" },
                    { 614, 25, 5, "Sylphic Vendor with \"Trusted\" Reputation with the tribe.", "Laurel Goobbue" },
                    { 615, 25, 5, "Legacy Chocobo is available to legacy players.", "Legacy Chocobo" },
                    { 616, 25, 5, "Rare drop in The Minstrel's Ballad: Shinryu's Domain.", "Legendary Kamuy" },
                    { 648, 25, 5, "18x Fae Fancy from Jul Oul", "Portly Porxie" },
                    { 617, 25, 5, "Received from the Behind Enemy Lines I Achievement.", "Logistics System" },
                    { 619, 25, 5, "In The Feast Rewards (Season 3), Top 100 Solo Ranking in a Datacenter.", "Lone Hellhound" },
                    { 620, 25, 5, "  Rare drop from The Minstrel's Ballad: Tsukuyomi's Pain.", "Lunar Kamuy" },
                    { 621, 25, 5, "Can be crafted by Carpenter Recipe 80★", "Magicked Bed" },
                    { 622, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Magicked Carpet" },
                    { 623, 25, 5, "Acquired after completing the Main Storyline.", "Magitek Armor" },
                    { 624, 25, 5, "Awarded from the achievement Die Another Day III.", "Magitek Avenger" },
                    { 625, 25, 5, "Complete \"Out of Hiding\" Achievement", "Magitek Avenger A-1" },
                    { 626, 25, 5, "In The Feast Rewards (Season 7), Top 100 Solo Ranking in a Datacenter.", "Magitek Conveyer" },
                    { 618, 25, 5, "In The Feast Rewards (Season 4), Top 100 Solo Ranking in a Datacenter.", "Lone Faehound" },
                    { 608, 25, 5, "Trade 12 Ixion Horns to Eschina.", "Ixion" },
                    { 649, 25, 5, "In The Feast Rewards (Season 8), Top 100 Party Ranking in a Datacenter.", "Prototype Conveyor" },
                    { 651, 25, 5, "50x Rathalos Scale+", "Rathalos" },
                    { 674, 25, 5, "15x Gold Chocobo Feathers, which are received from the Recruit a Friend Campaign.", "Twintania" },
                    { 675, 25, 5, "Bought at the Gold Saucer for 750,000 MGP", "Typhon" },
                    { 676, 25, 5, "The Forbidden Land, Eureka Anemos", "Tyrannosaur" },
                    { 677, 25, 5, "Purchased from Enie in The Firmament for 8,400 Skybuilders' Scrips", "Ufiti" },
                    { 678, 25, 5, "Unicorn can be acquired when you level Conjurer to 30 and complete the quest Unicorn Power.", "Unicorn" },
                    { 679, 25, 5, "Completion of the But Somebody's Gotta Do It (Dark Knight) achievement.", "War Panther" },
                    { 680, 25, 5, "Completion of the Tank you Gunbreaker II achievement.", "War Tiger" },
                    { 681, 25, 5, "Completion of the But Somebody's Gotta Do It (Warrior) achievement.", "Warbear" },
                    { 682, 25, 5, "Completion of the But Somebody's Gotta Do It (Paladin) achievement.", "Warlion" },
                    { 683, 25, 5, "Rare drop from Containment Bay S1T7 (Extreme).", "Warring Lanner" },
                    { 684, 25, 5, "Acquiring all 13 Yo-kai Weapons from the Yo-kai Watch: Gather One, Gather All! Seasonal Event.", "Whisper A-go-go" },
                    { 685, 25, 5, "Acquiring all 13 Yo-kai Minions from the Yo-kai Watch: Gather One, Gather All! Seasonal Event.", "Whisper-go" },
                    { 686, 25, 5, "Purchased from the Mog Station for EUR 8.40 or $12.", "White Devil" },
                    { 687, 25, 5, "Rare drop from The Limitless Blue (Extreme).", "White Lanner" },
                    { 688, 25, 5, "Purchased from the Mog Station for EUR 8.40 or $12.", "Witch's Broom" },
                    { 689, 25, 5, "Sold for 6 Clan Mark Logs from Bertana.", "Wyvern" },
                    { 690, 25, 5, "Dropped by Garuda in The Howling Eye (Extreme).", "Xanthos" },
                    { 673, 25, 5, "18x Ananta Dreamstaff from Madhura", "True Griffin" },
                    { 672, 25, 5, "Completion of the Nuts for Nutsy achievement.", "Triceratops" },
                    { 671, 25, 5, "Purchase Stormblood Collector's Edition.", "Syldra" },
                    { 670, 25, 5, "Purchased from Mog Station for EUR 8.40 or $12.", "Sunspun Cumulus" },
                    { 652, 25, 5, "Purchased from the Mog Station for EUR 8.40 or $12.", "Red Baron" },
                    { 653, 25, 5, "Purchased from the Mog Station for EUR 16.90 or $24.", "Red Hare" },
                    { 654, 25, 5, "Purchased for 200,000 MGP during the A Nocturne for Heroes Event", "Regalia Type-G" },
                    { 655, 25, 5, "Rare drop from The Pool of Tribute (Extreme) (Susano Ex).", "Reveling Kamuy" },
                    { 656, 25, 5, "Rare drop from Thok ast Thok (Extreme).", "Rose Lanner" },
                    { 657, 25, 5, "Rare drop from The Minstrel's Ballad: Thordan's Reign.", "Round Lanner" },
                    { 658, 25, 5, "Bought at Gold Saucer for 2,000,000 MGP", "Sabotender Emperador" },
                    { 659, 25, 5, "Front and Center V PvP Achievement", "Safeguard System" },
                    { 650, 25, 5, "Furious Fatalities PvP Achievement", "Raigo" },
                    { 660, 25, 5, "200,000 gil from Luna Vanu, at Rank 7 with the Vanu Vanu Beast Tribe.", "Sanuwa" },
                    { 662, 25, 5, "Completion of the A Line in the Glade IV achievement. ", "Serpent Warsteed" },
                    { 663, 25, 5, "Rare drop from The Minstrel's Ballad: Hades's Elegy", "Shadow Gwiber" },
                    { 664, 25, 5, "Rare drop from Eden's Gate: Sepulture (Savage)", "Skyslipper" },
                    { 665, 25, 5, "Purchased from the Mog Station for EUR 16.90 or $24.", "Sleipnir" },
                    { 666, 25, 5, "Dropped from Containment Bay P1T6 (Extreme).", "Sophic Lanner" },
                    { 667, 25, 5, "Completion of the A Line in the Storm IV achievement.", "Storm Warsteed" },
                    { 668, 25, 5, "Purchased from the Mog Station for EUR 8.40 or $12.", "Starlight Bear" },
                    { 669, 25, 5, "Bought from Shikitahe for 12x Kojin Sango. Bloodsworn Rep required.", "Striped Ray" },
                    { 661, 25, 5, "Purchased from the Mog Station for EUR 20 or $29.", "SDS Fenrir" },
                    { 607, 25, 5, "Purchased with 12x Formidable Cog from FATE Chain in Kholusia.", "Ironfrog Mover" },
                    { 606, 25, 5, "Trial reward for Innocence - Crown of the Immaculate (Extreme).", "Innocent Gwiber" },
                    { 605, 25, 5, "Purchased from the Mog Station for EUR 20 or $29.", "Indigo Whale" },
                    { 544, 25, 5, "750,000 MGP from Gold Saucer Attendant", "Archon Throne" },
                    { 545, 25, 5, "Dropped from Alexander - The Soul of the Creator (Savage) (A12S)", "Arrhidaeus" },
                    { 546, 25, 5, "Rewarded from the 2,000 Mentor Roulette Achievement", "Astrope" },
                    { 547, 25, 5, "Rarely from The Jade Stoa (Extreme).", "Auspicious Kamuy" },
                    { 548, 25, 5, "Awarded from the Achievement Tank You, Warrior III.", "Battle Bear" },
                    { 549, 25, 5, "Awarded from the Achievement Tank You, Paladin III.", "Battle Lion" },
                    { 550, 25, 5, "Awarded from the Achievement Tank You, Dark Knight III. ", "Battle Panther" },
                    { 551, 25, 5, "Completion of the Tank you Gunbreaker III achievement.", "Battle Tiger" },
                    { 552, 25, 5, "Achievement Certificates", "Behemoth" },
                    { 553, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Bennu" },
                    { 554, 25, 5, "Completion of Divine Intervention Heavensward Main Scenario Quest", "Black Chocobo" },
                    { 555, 25, 5, "From Gold-trimmed Sacks found in Floors 151 - 200 of Palace of the Dead.", "Black Pegasus" },
                    { 556, 25, 5, "Dropped from Emanation (Extreme) (Lakshmi Ex).", "Blissful Kamuy" },
                    { 557, 25, 5, "Kobold Vendor with \"Trusted\" Reputation with the tribe.", "Bomb Palanquin" },
                    { 558, 25, 5, "Dropped by Shiva in The Akh Afah Amphitheatre (Extreme)", "Boreas" },
                    { 559, 25, 5, "Valentione's Day (2018)", "Broken Heart (Left)" },
                    { 560, 25, 5, "Valentione's Day (2018)", "Broken Heart (Right)" },
                    { 543, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Aquamarine Carbuncle" },
                    { 542, 25, 5, "8x Gold Chocobo Feathers, which are received from the Recruit a Friend Campaign.", "Amber Draught Chocobo" },
                    { 541, 25, 5, "Completion of the Life of Adventure IV Achievement", "Amaro" },
                    { 540, 25, 5, "Drops from Deltascape V4.0 (Savage)", "Alte Roite" },
                    { 522, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Wind-up Warrior of Light" },
                    { 523, 25, 4, "Drops from The Ghimlyt Dark", "Wind-up Weapon" },
                    { 524, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Wind-up Y'shtola" },
                    { 525, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Wind-up Yda" },
                    { 526, 25, 4, "Bonus code from the Stormblood Art Book", "Wind-up Yotsuyu" },
                    { 527, 25, 4, "Acquired from The Rising (2015). MogStation: 5 USD / 3.5 EUR", "Wind-up Yugiri" },
                    { 528, 25, 4, "Fan Fest 2017 in Frankfurt Event/Live Stream Ticket", "Wind-up Yuna" },
                    { 529, 25, 4, "Potential Wondrous Tails reward", "Wind-up Zhloe" },
                    { 561, 25, 5, "Amalj'aa Vendor with \"Trusted\" Reputation with the tribe.", "Cavalry Drake" },
                    { 530, 25, 4, "30,000 gil and Rank 4 (Trusted Reputation) from Luna Vanu", "Wind-up Zundu Warrior" },
                    { 532, 25, 4, "The Forbidden Land, Eureka Hydatos", "Yukinko Snowflake" },
                    { 533, 25, 4, "Kojiin Beast Tribe Reward. Costs 5 Kojin Sango from Shikitahe.", "Zephyrous Zabuton" },
                    { 534, 25, 4, "Purchased from Gold Saucer Attendant for 10,000 MGP", "Zu Hatchling" },
                    { 535, 25, 5, "200,000 MGP from Gold Saucer Attendant (Prize Claim)", "Adamantoise" },
                    { 536, 25, 5, "Awarded from the Achievement In a Blaze of Glory V.", "Aerodynamics System" },
                    { 537, 25, 5, "Achievement Certificates", "Ahriman" },
                    { 538, 25, 5, "Guaranteed drop from Sigmascape V4.0 (Savage)", "Air Force" },
                    { 539, 25, 5, "Dropped by Ifrit in The Bowl of Embers (Extreme).", "Aithon" },
                    { 531, 25, 4, "Man's Best Friend quest in Aleport from Skribyld.", "Wolf Pup" },
                    { 562, 25, 5, "Sahagin Vendor with \"Trusted\" Reputation with the tribe.", "Cavalry Elbst" },
                    { 563, 25, 5, "You Got Game Hunt Achievement", "Centurio Tiger" },
                    { 564, 25, 5, "Obtain from Gold or Platinum Eternal Bond.", "Ceremony Chocobo" },
                    { 587, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Fat Moogle" },
                    { 588, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Fatter Cat" },
                    { 589, 25, 5, "1,000,000 MGP from Gold Saucer Attendant (Prize Claim)", "Fenrir" },
                    { 590, 25, 5, "Acquired all 7 Lanner mounts then complete the Fiery Wings, Fiery Hearts quest.", "Firebird" },
                    { 591, 25, 5, "Completion of the A Line in the Sand IV achievement.", "Flame Warsteed" },
                    { 592, 25, 5, "Crafted by Alchemist Level 70** with Master Alchemist V. ", "Flying Chair" },
                    { 593, 25, 5, "NA and JP special DLC Promotional Events", "Flying Cumulus" },
                    { 594, 25, 5, "Purchased with 3,200 Sacks of Nuts from Ilfroy", "Forgiven Reticence" },
                    { 586, 25, 5, "Obtained from A Realm Reborn Collector's Edition Bonuses.", "Fat Chocobo" },
                    { 595, 25, 5, "Completion of the Everybody's Darling achievement.", "Gilded Magitek Armor" },
                    { 597, 25, 5, "Completion of the You Are What You Eat IV achievement.", "Gloria-class Airship" },
                    { 598, 25, 5, "Drops from Alexander - The Burden of the Father (Savage) / A4S.", "Gobwalker" },
                    { 599, 25, 5, "Goobbue Mount is available only to 1.0 players.", "Goobbue" },
                    { 600, 25, 5, "Fatal Feast PvP Achievement", "Goten" },
                    { 601, 25, 5, "Purchasing the Collector's Edition of Shadowbringer.", "Grani" },
                    { 602, 25, 5, "Purchasing the Collector's Edition of Heavensward.", "Griffin" },
                    { 603, 25, 5, "Dropped by Titan in The Navel (Extreme).", "Gullfaxi" },
                    { 604, 25, 5, "Rare drop from the Wreath of Snakes (Extreme).", "Hallowed Kamuy" },
                    { 596, 25, 5, "Obtained from Frontline Fury Achievement.", "Ginga" },
                    { 520, 25, 4, "30,000 gil and Rank 4 (Trusted Reputation) from Vath Stickpeddler.", "Wind-up Vath" },
                    { 585, 25, 5, "Amazon Promotion", "Fat Black Chocobo" },
                    { 583, 25, 5, "Trial reward for Titania - Dancing Plague (Extreme).", "Fae Gwiber" },
                    { 565, 25, 5, "All Saint's Wake 2019", "Circus Ahriman" },
                    { 566, 25, 5, "Purchased from the Mog Station for EUR 16.80 or $24.", "Citrine Carbuncle" },
                    { 567, 25, 5, "200,000 gil from Mogmul Mogbelly, at Rank 7 (Sworn) with the Moogle Beast Tribe.", "Cloud Mallow" },
                    { 568, 25, 5, "Coeurl Mount is available to players who have purchased the Collector's Edition.", "Coeurl" },
                    { 569, 25, 5, "Completion of one of the My Little Chocobo Grand Company quests.", "Company Chocobo" },
                    { 570, 25, 5, "Awarded from the achievement One Steppe At A Time V", "Construct VII" },
                    { 571, 25, 5, "Rare drop from Nidhogg Extreme", "Dark Lanner" },
                    { 572, 25, 5, "Completion of the achievement We're on Your Side I", "Demi-Osma" },
                    { 584, 25, 5, "Acquired from Fly the Falcon Mount Campaign", "Falcon" },
                    { 573, 25, 5, "Drops from Containment Bay Z1T9 (Extreme) (Zurvan EX).", "Demonic Lanner" },
                    { 575, 25, 5, "Bought from E-Una-Kotor for 10x Gelmorran Potsherd.", "Disembodied Head" },
                    { 576, 25, 5, "Rarely from Platinum-haloed Sacks from Heaven-on-High", "Dodo" },
                    { 577, 25, 5, "Received from the Recruit a Friend Campaign.", "Draught Chocobo" },
                    { 578, 25, 5, "Purchased from the Mog Station for EUR 8.40 or $12.", "Eggshilaration System" },
                    { 579, 25, 5, "Forbidden Land, Eureka Pyros", "Eldthurs" },
                    { 580, 25, 5, "Dropped by Leviathan in The Whorleater (Extreme).", "Enbarr" },
                    { 581, 25, 5, "Trial reward for Hell's Kier (Extreme)", "Euphonious Kamuy" },
                    { 582, 25, 5, "Rarely drops from Eureka Hydatos bunny chest.", "Eurekan Petrel" },
                    { 574, 25, 5, "Ixali Vendor with \"Sworn\" Reputation with the tribe.", "Direwolf" },
                    { 347, 25, 4, "Emerald Carbuncle Plush", "Peridot Carbuncle" },
                    { 346, 25, 4, "Complete the The Road of Verminion I achievement", "Penguin Prince" },
                    { 345, 25, 4, "Acquired in The Diadem, dropped by Bloody Wings FATE.", "Pegasus Colt" },
                    { 111, 25, 3, "Little Ladies' Day (2018)", "Cheer Jump" },
                    { 112, 25, 3, "Little Ladies' Day (2018)", "Cheer On" },
                    { 113, 25, 3, "Little Ladies' Day (2018)", "Cheer Wave" },
                    { 114, 25, 3, "Treasure Maps - Lost Canals of Uznair", "Confirm" },
                    { 115, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Crimson Lotus" },
                    { 116, 25, 3, "Meister Quality Shiva Figure Order Bonus", "Diamond Dust" },
                    { 117, 25, 3, "Level 15 Valentione's Day (2017) quest \"Once More with Feeling\". MogStation: 2 USD / 1.4 EUR", "Dote" },
                    { 118, 25, 3, "Level 62 main quest \"Confederate Consternation\"", "Eastern Bow" },
                    { 119, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Eastern Dance" },
                    { 120, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Eastern Greeting" },
                    { 121, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Eastern Stretch" },
                    { 122, 25, 3, "Level 50 side quest \"An Egi by Any Other Name\"", "Egi Glamour" },
                    { 123, 25, 3, "Bought from the Storm Sergeant (Wolves' Den Provisioner) in Wolves' Den Pier for 15,000 Wolf Marks", "Elucidate" },
                    { 124, 25, 3, "Level 1 quest \"The Ties that Bind\".  Get married.", "Embrace" },
                    { 125, 25, 3, "Level 70 Main Quest \"The Call\"", "Endure" },
                    { 126, 25, 3, "Level 15 Make it Rain Campain (2016) quest \"An Inspector's Gadget\". MogStation: 2 USD / 1.4 EUR", "Eureka" },
                    { 127, 25, 3, "Received from the \"Recruit a Friend Campaign\" as either recruiter or recruited.", "Fist Bump" },
                    { 110, 25, 3, "Trade with Madhura at Castellum Velodyna", "Charmed" },
                    { 109, 25, 3, "Achievement \"Dear Leader I\"", "Breath Control" },
                    { 108, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Box Step" },
                    { 107, 25, 3, "Level 70 main quest \"Arenvald's Adventure\"", "Box" },
                    { 89, 25, 2, "Purchased from The Immortal Flames vendor for 6000 Company Seals.", "Ul'dahn Barding" },
                    { 90, 25, 2, "Immortal Flames Default Barding", "Ul'dahn Saddle" },
                    { 91, 25, 2, "Purchased from The Immortal Flames vendor for 8000 Company Seals.", "Ul'dahn Crested Barding" },
                    { 92, 25, 2, "Purchased from The Immortal Flames vendor for 4000 Company Seals.", "Ul'dahn Half Barding" },
                    { 93, 25, 2, "Achieve rank 10 with your chocobo with all 10 skill points in your healer skill tree.", "White Mage Barding" },
                    { 94, 25, 2, "3x Achievement Certificate from Jonathas in Apkallu Falls.", "Wild Rose Barding" },
                    { 95, 25, 2, "Drops from Kugane Ohashi Trial", "Yojimbo Barding" },
                    { 96, 25, 2, "Crafted  by Level 60???? Armorer", "Zurvanite Barding" },
                    { 128, 25, 3, "Duty \"The Forbidden Land, Eureka Hydatos\"", "Fist Pump" },
                    { 97, 25, 3, "Purchased from Kasumi at the Gold Saucer for 5,000 gil", "Aback" },
                    { 99, 25, 3, "Trade with Grand Company Quartermasters", "Attention" },
                    { 100, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Backflip" },
                    { 101, 25, 3, "Level 14 side quest \"Help Me, Lord of the Dance\"", "Ball Dance" },
                    { 102, 25, 3, "Level 60 main quest \"Causes and Costs\"", "Battle Stance" },
                    { 103, 25, 3, "Bought from the main counter in the Gold Saucer for 20,000 MPG", "Big Grin" },
                    { 104, 25, 3, "Moonfire Faire (2016), MogStation: 3 USD / 2.1 EUR", "Black Ranger Pose A" },
                    { 105, 25, 3, "Moonfire Faire (2016), MogStation: 3 USD / 2.1 EUR", "Black Ranger Pose B" },
                    { 106, 25, 3, "Moonfire Faire (2014), MogStation: 2 USD / 1.4 EUR", "Bomb Dance" },
                    { 98, 25, 3, "Trade with Grand Company Quartermasters", "At Ease" },
                    { 88, 25, 2, "Level 80? Armorer recipe.", "Titania Barding" },
                    { 129, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Get Fantasy" },
                    { 131, 25, 3, "Level 70 side quest \"What a Wonder-full World\"", "Gratuity" },
                    { 154, 25, 3, "Moonfire Faire (2016), MogStation: 3 USD / 2.1 EUR", "Red Ranger Pose B" },
                    { 155, 25, 3, "10,000 Company Seals", "Reflect" },
                    { 156, 25, 3, "15,0000 Wolf Marks Exchange", "Reprimand" },
                    { 157, 25, 3, "Trade with Shikitahe in Tamamizu", "Ritual Prayer" },
                    { 158, 25, 3, "Duty \"The Forbidden Land, Eureka Pyros\"", "Scheme" },
                    { 159, 25, 3, "\"Make It Rain\" 2019 Event", "Senor Sabotender" },
                    { 160, 25, 3, "Duty \"The Forbidden Land, Eureka Pagos\"", "Shiver" },
                    { 161, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Side Step" },
                    { 162, 25, 3, "Achievement \"Dear Leader I\"", "Sit-ups" },
                    { 163, 25, 3, "Little Ladies' Day (2017), MogStation: 2 USD / 1.4 EUR", "Songbird" },
                    { 164, 25, 3, "Level 60 side story quest \"Letters from No One\"", "Spectacles" },
                    { 165, 25, 3, "Moonfire Faire (2018), MogStation: 3 USD / 2.1 EUR", "Splash" },
                    { 166, 25, 3, "Achievement \"Dear Leader I\"", "Squats" },
                    { 167, 25, 3, "Level 14 side quest \"Good for What Ales You\"", "Step Dance" },
                    { 168, 25, 3, "Level 50 Vanu Vanu quest \"Sundrop the Beat\"", "Sundrop Dance" },
                    { 169, 25, 3, "Trade with Confederate Custodian in Crick.", "Sweat" },
                    { 170, 25, 3, "Bought from the main counter in the Gold Saucer for 80,000 MPG", "Thavnairian Dance" },
                    { 153, 25, 3, "Moonfire Faire (2016), MogStation: 3 USD / 2.1 EUR", "Red Ranger Pose A" },
                    { 152, 25, 3, "Achievement \"Dear Leader I\"", "Push-ups " },
                    { 151, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Pretty Please" },
                    { 150, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Power Up" },
                    { 132, 25, 3, "Level 70 main quest \"Tidings from the East\"", "Greeting" },
                    { 133, 25, 3, "Level 14 side quest \"Saw That One Coming\"", "Harvest Dance" },
                    { 134, 25, 3, "Level 60 side quest \"The Burdens We Bear\"", "Haurchefant" },
                    { 135, 25, 3, "Purchased from Maudlin Latool Ja in Ul'dah for 400 Allied Seals", "Headache" },
                    { 136, 25, 3, "Quest \"Hell's Kier (Normal)\"", "Hum" },
                    { 137, 25, 3, "Level 15 The Rising (2014) quest \"What Blooms in the Night\". MogStation: 2 USD / 1.4 EUR", "Huzzah" },
                    { 138, 25, 3, "Level 45 main quest \"Acting the Part\"", "Imperial Salute" },
                    { 139, 25, 3, "Sidequest chain continuing on form lvl 78 Aether Current quest", "Lali-ho" }
                });

            migrationBuilder.InsertData(
                table: "CollectionTask",
                columns: new[] { "Id", "CategoryId", "CollectionTypeId", "Method", "Name" },
                values: new object[,]
                {
                    { 130, 25, 3, "Bought from the main counter in the Gold Saucer for 80,000 MPG", "Gold Dance" },
                    { 140, 25, 3, "Purchased from Enie in The Firmament for 1,800 Skybuilders' Scrips", "Lean" },
                    { 142, 25, 3, "Level 70 side story quest \"Don't Do the Dewprism\"", "Manderville Mambo" },
                    { 143, 25, 3, "Mogstation: 12 USD / 9 EUR", "Megaflare" },
                    { 144, 25, 3, "Level 50 moogle quest \"Piecing Together the Past\"", "Moogle Dance" },
                    { 145, 25, 3, "Level 60 side story quest \"Eternity, Loyalty, Honesty\"", "Moonlift Dance" },
                    { 146, 25, 3, "Level 50 side story quest \"Her Last Vow\"", "Most Gentlemanly" },
                    { 147, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Play Dead" },
                    { 148, 25, 3, "Level 70 main quest \"Emmisary of the Dawn\"", "Ponder" },
                    { 149, 25, 3, "MogStation: 7 USD / 4.9 EUR", "Popoto Step" },
                    { 141, 25, 3, "Level 50 side story quest \"The Hammer\"", "Manderville Dance" },
                    { 87, 25, 2, "Can be crafted from recipe by a level 50??? Armorer", "Tidal Barding" },
                    { 86, 25, 2, "Can be crafted by Armorer Recipe 70????", "Suzaku Barding" },
                    { 85, 25, 2, "Acquired through Starlight Celebration (2013) Seasonal Event.", "Starlight Barding" },
                    { 24, 25, 2, "From Gold and Silver Trimmed Sacks found in Palace of the Dead.", "Abigail Barding" },
                    { 25, 25, 2, "Acquired through the \"Rattle and Humbaba\" FATE in The Peaks.", "Ala Mhigan Barding" },
                    { 26, 25, 2, "Purchased from the Mog Station for EUR 7 or $10.", "Angelic Barding" },
                    { 27, 25, 2, "3x Achievement Certificate from Jonathas in Apkallu Falls.", "Barding of Light" },
                    { 28, 25, 2, "Acquired through the purchase of Final Fantasy XIV A Realm Reborn Collector's Edition.", "Behemoth Barding" },
                    { 29, 25, 2, "3x Achievement Certificate from Jonathas in Apkallu Falls.", "Black Mage Barding" },
                    { 30, 25, 2, "Can be crafted by Goldsmith Recipe 70?", "Blissful Barding" },
                    { 31, 25, 2, "Purchased from the Mog Station for EUR 7 or $10.", "Butlery Barding" },
                    { 32, 25, 2, "Can be crafted by Goldsmith Recipe 70???", "Byakko Barding" },
                    { 33, 25, 2, "Trade 1,650 Yellow Gatherers' Scrip at an Exchange", "Chocobo Raincoat" },
                    { 34, 25, 2, "Purchased with 350x Bicolour Gemstone (Eulmore)", "Dancer Barding" },
                    { 35, 25, 2, "Purchased with 350x Bicolour Gemstone (Lakeland)", "Deepshadow Barding" },
                    { 36, 25, 2, "Purchased from the Mog Station for EUR 7 or $10.", "Demonic Barding" },
                    { 37, 25, 2, "Obtain a level 10 Attacker Chocobo Companion.", "Dragoon Barding" },
                    { 38, 25, 2, "Purchased from the Mog Station for EUR 4.90 or $7.", "Eerie Barding" },
                    { 39, 25, 2, "Acquired through 2014 Hatching-tide seasonal event.", "Egg Harness" },
                    { 40, 25, 2, "Purchased from the Mog Station for EUR 4.90 or $7.", "Egg Hunter Barding" },
                    { 23, 25, 1, "Purchase Modern Cosmetics: A Wicked Wake for EUR 4.90 or $7 USD", "Spiderweb" },
                    { 22, 25, 1, "Purchase Modern Cosmetics: A Wicked Wake for EUR 4.90 or $7 USD", "Bats" },
                    { 21, 25, 1, "Purchased from Storm Sergeant - Wolves' Den Provisioner for 18,000 Wolf Marks", "Styled for Hire" },
                    { 20, 25, 1, "Art or Costume contests for Fan Festival 2018", "Strife" },
                    { 2, 25, 1, "Purchase from Gold Saucer Attendant for 9,600 MPG", "Curls" },
                    { 3, 25, 1, "Progression through \"The Ties that Bind\" quest for $0-$20 USD (Available on all plans)", "Eternal Bonding " },
                    { 4, 25, 1, "Purchased from Storm Sergeant - Wolves' Den Provisioner for 18,000 Wolf Marks", "Fashionably Feathered" },
                    { 5, 25, 1, "Drops from Eureka Pyros", "Form and Function" },
                    { 6, 25, 1, "Purchase from Gold Saucer Attendant for 30,000 MPG", "Great Lengths" },
                    { 7, 25, 1, "Drops from Heaven-on-High", "Gyr Abanian Plait" },
                    { 8, 25, 1, "Purchase from Gold Saucer Attendant for 50,000 MPG after finishing \"The City of Lost Angels\" & \"The Orbonne Monastery\"", "Lexen-tails" },
                    { 9, 25, 1, "Purchased from Ironworks Vendor for 20,000 MGP after completeing \"Messenger of the Winds\"", "Lucian Locks" },
                    { 41, 25, 2, "Can be crafted by Armorer Recipe 60?", "Expanse Barding" },
                    { 10, 25, 1, "Purchase \"Aymeric's Attire\" for $15", "Master & Commander" },
                    { 12, 25, 1, "Purchase from Gold Saucer Attendant for 8,000 MPG", "Ponytails" },
                    { 13, 25, 1, "Purchase \"Lightning's Attire\" or \"Snow's Attire\" for $15", "Pulse - Lightning Hairstyle" },
                    { 14, 25, 1, "Purchase \"Lightning's Attire\" or \"Snow's Attire\" for $15", "Pulse - Snow's Hairstyle" },
                    { 15, 25, 1, "Purchase from Event NPC for 5,000 MPG", "Rainmaker" },
                    { 16, 25, 1, "Drops from Palace of the Dead", "Samsonian Locks" },
                    { 17, 25, 1, "Purchase \"Minfilia's Attire\" for $15", "Scion Special Issue" },
                    { 18, 25, 1, "Purchase \"Thancred's Modish Attire\" for $15", "Scion Special Issue II" },
                    { 19, 25, 1, "Purchase \"Y'shtola Modish Attire\" for $15", "Scion Special Issue III" },
                    { 11, 25, 1, "Purchase from Enie for 1,800 Skybuilders' Scrips", "Modern Legend" },
                    { 42, 25, 2, "Purchased from the Mog Station for EUR 7 or $10.", "Far East Barding" },
                    { 43, 25, 2, "Complete \"I Believe I Can Fly\" Quest", "Flyer Shaffron" },
                    { 44, 25, 2, "Purchase from Gold Saucer Attendant for 20,000 MGP.", "Gambler Barding" },
                    { 67, 25, 2, "The \"Do you even /Pose?\" Forum Hairstyle Design Contest", "Noble Barding" },
                    { 68, 25, 2, "Unknown", "Oriental Barding" },
                    { 69, 25, 2, "Can be crafted by a level 56 Weaver Recipe", "Orthodox Barding" },
                    { 70, 25, 2, "Obtain a level 10 Defender Chocobo Companion.", "Paladin Barding" },
                    { 71, 25, 2, "Acquired after completing the quests during the Valentione's Day (2015).", "Paramour Barding" },
                    { 72, 25, 2, "Obtain the Breaking Bo achievement ", "Plumed Barding" },
                    { 73, 25, 2, "Acquired from the achievement Ride to the Challenge I", "Race Barding" },
                    { 74, 25, 2, "Aquired from duty \"The Forbidden Land, Eureka Anemos\"", "Red Mage Barding" },
                    { 66, 25, 2, "Purchased from the Mog Station for EUR 7 or $10.", "Nezha Barding" },
                    { 75, 25, 2, "Can be crafted by Armorer Recipe 70?", "Reveler's Barding" },
                    { 77, 25, 2, "Acquired through Starlight Celebration (2019) Seasonal Event.", "Saintly Barding" },
                    { 78, 25, 2, "Aquired from The Forbidden Land, Eureka Pyros", "Samurai Barding" },
                    { 79, 25, 2, "Can be crafted by Armorer Recipe 70????", "Seiryu Barding" },
                    { 80, 25, 2, "Can be crafted by Leatherworker Recipe 60??", "Sephirotic Barding" },
                    { 81, 25, 2, "Can be crafted by Armorer Recipe 70??", "Shinryu Barding" },
                    { 82, 25, 2, "5 Odin's Mantle, from completing the Odin FATE, to Aelina in Mor Dhona (22,6).", "Sleipnir Barding" },
                    { 83, 25, 2, "Level 60???? Goldsmith recipe.", "Sophic Barding" },
                    { 84, 25, 2, "Awarded after receiving 300 player commendations.", "Sovereign Barding" },
                    { 76, 25, 2, "15 Heavens' Ward Helm Fragments traded at Rowena's Center for Cultural Promotion", "Round Table Barding" },
                    { 171, 25, 3, "Level 36 side quest \"Toss Fit Workout\"", "Throw" },
                    { 65, 25, 2, "Purchased from Gold Saucer Attendant for 150,000 MGP.", "Mandervillian Barding" },
                    { 63, 25, 2, "Maelstrom Default Barding", "Lominsan Saddle" },
                    { 45, 25, 2, "Purchased from The Order of the Twin Adder vendor for 6000 Company Seals.", "Gridanian Barding" },
                    { 46, 25, 2, "Purchased from The Order of the Twin Adder vendor for 8000 Company Seals.", "Gridanian Crested Barding" },
                    { 47, 25, 2, "Purchased from The Order of the Twin Adder vendor for 4000 Company Seals.", "Gridanian Half Barding" },
                    { 48, 25, 2, "Order of the Twin Adder Default Barding", "Gridanian Saddle" },
                    { 49, 25, 2, "Can be crafted by Armorer Recipe 80??", "Hades Barding" },
                    { 50, 25, 2, "Can be crafted by a Level 40 Leatherworker Recipe", "Highland Barding" },
                    { 51, 25, 2, "Obtained from Eschina in Rhalgr's Reach for 4 Veteran Clan Mark Logs.", "Hingan Barding" },
                    { 52, 25, 2, "Can be crafted by Armorer Recipe 60?", "Hive Barding" },
                    { 64, 25, 2, "Can be crafted by Weaver Recipe 70???", "Lunar Barding" },
                    { 53, 25, 2, "Can be crafted by Leatherworker Recipe 60???", "Horde Barding" },
                    { 55, 25, 2, "Level 80? Armorer recipe.", "Innocence Barding" },
                    { 56, 25, 2, "Purchased with 350 Centurio Seals, obtained from Clan Hunts from Ardolain in Foundation", "Ishgardian Barding" },
                    { 57, 25, 2, "Obtained from Level 56 FATE Vedrfolnir Devoteth in The Churning Mists (11,36).", "Ishgardian Half Barding" },
                    { 58, 25, 2, "5 Ixion Horns, acquired from A Horse Outside FATE, to Eschina in Rhalgr's Reach", "Ixion Barding" },
                    { 59, 25, 2, "Can be crafted by Leatherworker Recipe 50???", "Levin Barding" },
                    { 60, 25, 2, "Purchased from The Maelstrom vendor for 6000 Company Seals.", "Lominsan Barding" },
                    { 61, 25, 2, "Purchased from The Maelstrom vendor for 8000 Company Seals.", "Lominsan Crested Barding" },
                    { 62, 25, 2, "Purchased from The Maelstrom vendor for 4000 Company Seals.", "Lominsan Half Barding" },
                    { 54, 25, 2, "Can be crafted by Leatherworker Recipe 50????", "Ice Barding" },
                    { 172, 25, 3, "Connect your account to the FFXIV mobile app", "Tomestone" },
                    { 173, 25, 3, "Trade with Eschidna in Rhalgr's Reach", "Tremble" },
                    { 174, 25, 3, "Meister Quality Ultima Figure order bonus", "Ultima" },
                    { 284, 25, 4, "Dropped from Silver Coffer in The Diadem of the Exploratory Missions.", "Hunting Hawk" },
                    { 285, 25, 4, "Complete the FATE Go, Go, Gorgimera with a Gold Medal rating", "Infant Imp" },
                    { 286, 25, 4, "Crafted by level 60★ Armorer.", "Iron Dwarf" },
                    { 287, 25, 4, "Pruchased from Fathard in Eulmore Aetheryte Plaze for 6 Formidable Cogs", "Ironfrog Ambler" },
                    { 288, 25, 4, "Rare drop in chest after final boss of Temple of the Fist.", "Ivon Coeurlfist Doll" },
                    { 289, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Jibanyan" },
                    { 290, 25, 4, "Gathered by level 46-50 Botanist", "Kidragora" },
                    { 291, 25, 4, "Woodland Exploration XXII Botanist Retainer Venture or Quick Exploration", "Koala Joey" },
                    { 292, 25, 4, "2x Achievement Certificate from Jonathas.", "Komainu" },
                    { 293, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Komajiro" },
                    { 294, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Komasan" },
                    { 295, 25, 4, "Rarely found in chest after final boss of Saint Mocianne's Arboretum.", "Korpokkur Kid" },
                    { 296, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Kyubi" },
                    { 297, 25, 4, "Found in chest after final boss of The Aery.", "Lesser Panda" },
                    { 298, 25, 4, "Randomly drops from chest in The Grand Cosmos", "Little Leannan" },
                    { 299, 25, 4, "2018 All Saint's Wake", "Little Yang" },
                    { 300, 25, 4, "2018 All Saint's Wake", "Little Yin" },
                    { 283, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Hovernyan" },
                    { 282, 25, 4, "Acquired from the Starlight Celebration (2014). MogStation: 5 USD / 3.5 EUR", "Hoary the Snowman" },
                    { 281, 25, 4, "Mama Said Knock You Out III (300 KO's in The Feast)", "Hellpup" },
                    { 280, 25, 4, "Topaz Carbuncle Plush", "Heliodor Carbuncle" },
                    { 262, 25, 4, "Purchased from Auriana for 7 Allagan Tomestones of Soldiery", "Fledgling Dodo" },
                    { 263, 25, 4, "Drops from Mt. Gulg", "Forgiven Hate" },
                    { 264, 25, 4, "Purchased for 3x Sassho-seki Fragments from Eschina", "Fox Kit " },
                    { 265, 25, 4, "10 Empyrean Potsherds from Confederate Custodian", "Frilled Dragon" },
                    { 266, 25, 4, "Found in chest after final boss of Sohm Al.", "Gaelikitten" },
                    { 267, 25, 4, "By intercrossing:   Garlic Clove with Mandrake", "Garlic Jester" },
                    { 268, 25, 4, "Heaven-on-High Silver-haloed Sack or Waterside Exploration XVIII or XIX Fisher Retainer Venture", "Gestahl" },
                    { 269, 25, 4, "Rare drop from The Sirensong Sea", "Ghido" },
                    { 301, 25, 4, "Woodland Exploration XIV-XVIII Botanist Retainer Venture", "Littlefoot" },
                    { 270, 25, 4, "1x Dancing Wing from Dancing Plague", "Giant Beaver" },
                    { 272, 25, 4, "Complete Further Hildibrand Adventures Quest: If I Could Turn Back Time.", "Gigi" },
                    { 273, 25, 4, "Complete On Dangerous Ground with a Gold Medal rating.", "Gold Rush Minecart" },
                    { 274, 25, 4, "Complete the Level 33 Main Scenario Quest \"It Was a Very Good Year\".", "Goobbue Sproutling" },
                    { 275, 25, 4, "Crafted by Level 50 Goldsmith.", "Gravel Golem" },
                    { 276, 25, 4, "400 Centurio Seals from Ardolain", "Griffin Hatchling" },
                    { 277, 25, 4, "Purchased from Gold Saucer Attendant for 20,000 MGP", "Heavy Hatchling" },
                    { 278, 25, 4, "3 Gelmorran Potsherds from E-Una-Kotor in Quarrymill", "Hecteye" },
                    { 279, 25, 4, "Canals/Altars of Uznair", "Hedgehoglet" },
                    { 271, 25, 4, "Rare fishing catch from The Burning Wall in Eastern Thanalan (28-25) with Topwater Frog.", "Gigantpole" },
                    { 302, 25, 4, "Crafted by Level 50★★★ Carpenter.", "Magic Broom" },
                    { 303, 25, 4, "Found in South Banepool with Snagging On and Brute Leech as bait.", "Magic Bucket" },
                    { 304, 25, 4, "Rare drop from level 69 dungeon Castrum Abania.", "Magitek Avenger F1" },
                    { 327, 25, 4, "Found in chest after final boss of The Lost City of Amdapor (Hard).", "Morpho" },
                    { 328, 25, 4, "Hatching-Tide (2018)", "Motley Egg" },
                    { 329, 25, 4, "St Mocianne's Arboretum (Hard)", "Mudpie" },
                    { 330, 25, 4, "Rarely found in chest after final boss of The Sunken Temple of Qarn (Hard).", "Mummy's Little Mummy" },
                    { 331, 25, 4, "Field Exploration XXV Combat Retainer Venture or Quick Exploration", "Mystic Weapon" },
                    { 332, 25, 4, "Libra Eorzea (Lore Book) Bonus Code", "Namingway" },
                    { 333, 25, 4, "Crafted by Level 50★★★★ Weaver.", "Nana Bear" },
                    { 334, 25, 4, "Found in last chest before final boss of Hullbreaker Isle at (5,10).", "Naughty Nanka" },
                    { 326, 25, 4, "Found in third chest of The Aurum Vale.", "Morbol Seedling" },
                    { 335, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Noko" },
                    { 337, 25, 4, "Heaven-on-High Silver or Gold-haloed Sacks or Highland, Waterside, or Woodland Exploration XIX-XXII Retainer Venture or Quick Exploration", "Odder Otter" },
                    { 338, 25, 4, "Alphascape V4.0", "OMG" },
                    { 339, 25, 4, "By intercrossing: Azeyma Rose with Krakka Root OR Krakka Root with mandrake", "Onion Prince" },
                    { 340, 25, 4, "Found in chest after final boss of The Fractal Continuum.", "Owlet" },
                    { 341, 25, 4, "Found in chest after final boss of The Great Gubal Library.", "Page 63" },
                    { 342, 25, 4, "Dragonskin Treasure Map, The Aquapolis, or Bronze-trimmed Sacks from Palace of the Dead", "Paissa Brat" },
                    { 343, 25, 4, "The New King on the Block MHW cross-over quest", "Palico" },
                    { 344, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Panda Cub" },
                    { 336, 25, 4, "Unhidden Treasure Map, or The Aquapolis", "Nutkin" },
                    { 261, 25, 4, "Completing all 80 A Realm Reborn Sightseeing Log Entries", "Fledgling Apkallu" },
                    { 325, 25, 4, "Rare drop from The Swallow's Compass (Duty).", "Monkey King" },
                    { 323, 25, 4, "Level 50★★★★ Blacksmith recipe", "Model Magitek Bit" },
                    { 305, 25, 4, "Highland Exploration XXII Miner Retainer Venture or Quick Exploration", "Mameshiba" },
                    { 306, 25, 4, "Purchased from Bango Zango in Limsa Lominsa, Roarich in Ul'dah, or Maisenta in New Gridania.", "Mammet #001" },
                    { 307, 25, 4, "Talk to Jonathas in Old Gridania after completing Bump on a Log: Order of the Twin Adder", "Mammet #003G" },
                    { 308, 25, 4, "Talk to Jonathas in Old Gridania after completing Bump on a Log: Maelstrom", "Mammet #003L" },
                    { 309, 25, 4, "Talk to Jonathas in Old Gridania after completing Bump on a Log: Immortal Flames", "Mammet #003U" },
                    { 310, 25, 4, "By intercrossing: Mandrake with Nymeia Lily", "Mandragora Queen" },
                    { 311, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Manjimutt" },
                    { 312, 25, 4, "Subaquatic Voyages - Coldtoe Isle", "Meerkat" },
                    { 324, 25, 4, "Crafted by Level 50 Goldsmith.", "Model Vanguard" },
                    { 313, 25, 4, "400x Bicolour Gemstone (Amh Araeng)", "Micro Gigantender" },
                    { 315, 25, 4, "Complete the Delivery Moogle Quests Thwack-a-Mole.", "Mini Mole" },
                    { 316, 25, 4, "Heaven-on-High Silver-haloed Sack or Highland Exploration XIV Miner Retainer Venture", "Miniature Minecart" },
                    { 317, 25, 4, "Purchased from Enie in The Firmament for 1,200 Skybuilders' Scrips", "Miniature White Knight" },
                    { 318, 25, 4, "Obtained from Jonathas in Old Gridania ( X:10.6 Y:6.3) for 2 Achievement Certificates.", "Minion of Light" },
                    { 319, 25, 4, "Exchanged for 15,000 Wolf Marks", "Minitek Conveyer" },
                    { 320, 25, 4, "The Aquapolis, Palace of the Dead Bronze-trimmed Sack, or Field, Highland, or Waterside Exploration XIII Retainer Venture", "Minute Mindflayer" },
                    { 321, 25, 4, "Rare drop from Doma Castle", "Mock-up Grynewaht" },
                    { 322, 25, 4, "The Art Of Eorzea, A Final Fantasy XIV Art Book", "Model Enterprise" },
                    { 314, 25, 4, "Complete the Main Scenario Quest The Rising Chorus.", "Midgardsormr" },
                    { 691, 25, 5, "In the Footsteps of Bardam the Brave Stormblood Main Scenario Quest", "Yol" },
                    { 260, 25, 4, "Purchased for 20,000 Flame Seals", "Flame Hatchling" },
                    { 258, 25, 4, "Obtained from Alexander - The Burden of the Son (Savage)", "Faustlet" },
                    { 197, 25, 4, "Found in chest after final boss of Brayflox's Longstop (Hard).", "Baby Opo-opo" },
                    { 198, 25, 4, "Boughbury Trader for 2400 if Clearing the Hive has been won.", "Baby Raptor" },
                    { 199, 25, 4, "Woodland Exploration XXV Botanist Retainer Venture or Quick Exploration", "Bacon Bits" },
                    { 200, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Beady Eye" },
                    { 201, 25, 4, "400 Centurio Seals from Ardolain", "Behemoth Heir" },
                    { 202, 25, 4, "Randomly drops from chest in The Wanderer's Palace.", "Bite-Sized Pudding" },
                    { 203, 25, 4, "800x Sacks of Nuts", "Bitty Duckbill" },
                    { 204, 25, 4, "Obtained from Jonathas in Old Gridania for 2 Achievement Certificates.", "Black Chocobo Chick" },
                    { 205, 25, 4, "Purchased from Gold Saucer Attendant for 20,000 MGP ", "Black Coeurl" },
                    { 206, 25, 4, "Drops from Holminster Switch Duty", "Black Hayate" },
                    { 207, 25, 4, "Acquired from Yo-kai Watch: Gather One, Gather All!.", "Blizzaria" },
                    { 208, 25, 4, "Obtained from Timeworn Peisteskin Map.", "Bluebird" },
                    { 209, 25, 4, "Heaven-on-High Silver-haloed Sack or Field Exploration XX and XXII Combat Retainer Venture or Quick Exploration", "Bom Boko" },
                    { 210, 25, 4, "Rare drop from Shisui of the Violet Tides", "Bomb Fish" },
                    { 211, 25, 4, "The Rising 2019", "Brave New Y'shtola" },
                    { 212, 25, 4, "Gift for attendees of an Eternal Bonding Anniversary", "Bridesmoogle" },
                    { 213, 25, 4, "Found in chest after final boss of The Antitower.", "Brina" },
                    { 196, 25, 4, "Preordering Shadowbringers", "Baby Gremlin" },
                    { 195, 25, 4, "Complete the FATE: Lazy for You with Gold Medal rating in East Shroud (23x y29).", "Baby Bun" },
                    { 194, 25, 4, "Randomly received from completing the Secret of the Lost Legend Boss FATE in The Diadem", "Baby Brachiosaur" },
                    { 193, 25, 4, "Purchase the collectors edition of FFXIV (1.0 or ARR)", "Baby Behemoth" },
                    { 175, 25, 3, "Level 60 main quest \"A Spectacle for the Ages\"", "Victory" },
                    { 176, 25, 3, "Level 63 main quest \"In Soroban We Trust\"", "Water Flip" },
                    { 177, 25, 3, "Trade with Eschidna in Rhalgr's Reach", "Winded" },
                    { 178, 25, 3, "Moonfire Faire (2016), MogStation: 3 USD / 2.1 EUR", "Yellow Ranger Pose A" },
                    { 179, 25, 3, "Moonfire Faire (2016), MogStation: 3 USD / 2.1 EUR", "Yellow Ranger Pose B" },
                    { 180, 25, 3, "Trade with Gyosho in Dhoro Iloh", "Yol Dance" },
                    { 181, 25, 3, "Item code from purchasing Meister Quality Odin Figure", "Zantetsuken" },
                    { 182, 25, 4, "Deep Sea Site 7 Voyage", "Abroader Otter" },
                    { 214, 25, 4, "Complete the Level 50 Main Scenario Quest \"You're Gonna Carry That\".", "Buffalo Calf" },
                    { 183, 25, 4, "Complete the Level 60 sidequest Do It for Gilly.", "Accompaniment Node" },
                    { 185, 25, 4, "Body and Soul Anima Relic Weapon Quest", "Anima" },
                    { 186, 25, 4, "Drops from Malikah's Well Duty", "Armadillo Bowler" },
                    { 187, 25, 4, "Obtained from Desynthesizing of Ninja Betta.", "Assassin Fry" },
                    { 188, 25, 4, "Crafted by Level 60★ Alchemist.", "Atrophied Atomos" },
                    { 189, 25, 4, "Bought for 7 Namazu Koban from Gyosho at Trusted (or higher) Beast Tribe Reputation.", "Attendee #777" },
                    { 190, 25, 4, "Subaquatic Voyages", "Aurelia Polyp" },
                    { 191, 25, 4, "Waterside Exploration XXII Fisher Retainer Venture or Quick Exploration", "Axolotl Eft" },
                    { 192, 25, 4, "From Junkmonger Nonoroon for 2,400 gil in Poor Maid's Mill, Upper La Noscea (11.8,24.7).", "Baby Bat" },
                    { 184, 25, 4, "Acquired in Valentione's Day (2017). MogStation: 5 USD / 3.5 EUR", "Angel of Mercy" },
                    { 215, 25, 4, "Rarely found in chest after final boss of Baelsar's Wall.", "Bullpup" },
                    { 216, 25, 4, "Purchased from Nacille in Fanow for 400 Bicolor Gemstones", "Butterfly Effect" },
                    { 217, 25, 4, "Levle 70★★ Weaver recipe.", "Byakko Cub" },
                    { 240, 25, 4, "Found in first chest of Amdapor Keep.", "Demon Brick" },
                    { 241, 25, 4, "Forbidden Land, Eureka Pyros", "Dhalmel Calf" },
                    { 242, 25, 4, "Waterside Exploration XXV Fisher Retainer Venture or Quick Exploration", "Domakin" },
                    { 243, 25, 4, "MogStation: 5 USD / 3.5 EUR", "Doman Magpie" },
                    { 244, 25, 4, "Wondrous Tails 2-line Reward", "Dress-up Alisaie" },
                    { 245, 25, 4, "Purchased from Enie in The Firmament for 1,200 Skybuilders' Scrips", "Dress-up Estinien" },
                    { 246, 25, 4, "Complete the Level 70 Main Scenario Quest Return of the Bull.", "Dress-up Raubahn" },
                    { 247, 25, 4, "Bonus code from the Art of the Revolution - Eastern Memories Art Book", "Dress-up Tataru" },
                    { 239, 25, 4, "Attending an Eternal Bond ceremony of Gold or Platinum tier.", "Demon Box" },
                    { 248, 25, 4, "Wondrous Tails 2-line Reward", "Dress-up Thancred" },
                    { 250, 25, 4, "Rarely found in the final chest of Kugane Castle", "Dress-up Yugiri" },
                    { 251, 25, 4, "Purchased from Auriana for Tomestones, or from Hatching-tide (2016)", "Dust Bunny" },
                    { 252, 25, 4, "Dropped in The Aquapolis.", "Dwarf Rabbit" },
                    { 253, 25, 4, "Dropped in Eden's Gate: Sepulture", "Eden Minor" },
                    { 254, 25, 4, "By intercrossing: Krakka Root with Star Anise OR Wizard Eggplant with Mandrake", "Eggplant Knight" },
                    { 255, 25, 4, "Obtained from Battle in the Big Keep.", "Enkidu" },
                    { 256, 25, 4, "How Can I Help III (300 assists in The Feast)", "Faepup" },
                    { 257, 25, 4, "Waterside Exploration XIV-XIX Fisher Retainer Venture", "Fat Cat" },
                    { 249, 25, 4, "Acquired from The Rising (2016). MogStation: 5 USD / 3.5 EUR", "Dress-up Y'shtola" },
                    { 259, 25, 4, "Randomly dropped after The Feast matches.", "Fenrir Pup" },
                    { 238, 25, 4, "Purchased from Maudlin Latool Ja in Ul'dah for 400 Allied Seals (Requires Level 60 BLU)", "Cute Justice" },
                    { 236, 25, 4, "Acquired from All Saints' Wake (2016). MogStation: 5 USD / 3.5 EUR", "Continental Eye" },
                    { 218, 25, 4, "Complete the quest Zombies Are People Too in Southern Thanalan", "Cactuar Cutting" },
                    { 219, 25, 4, "Received for pre-ordering FFXIV: ARR (CE or SE)", "Cait Sith Doll" },
                    { 220, 25, 4, "Rarely found in chest after final boss of Hullbreaker Isle (Hard).", "Calamari" },
                    { 221, 25, 4, "Found in chest after final boss of The Antitower.", "Calca" },
                    { 222, 25, 4, "The Lost Canals of Uznair", "Capybara Pup" },
                    { 223, 25, 4, "Fished from Fishing Log: Isle of Endless Summer North Shore", "Castaway Chocobo Chick" },
                    { 224, 25, 4, "Drops from The Qitana Ravel Duty", "Chameleon" },
                    { 225, 25, 4, "Purchased from Bango Zango in Limsa Lominsa, Roarich in Ul'dah, or Maisenta in New Gridania.", "Cherry Bomb" },
                    { 237, 25, 4, "Rare drop from lockboxes in Eureka: Pagos", "Copycat Bulb" },
                    { 226, 25, 4, "Complete the quest Occupational Hazards from Yoenne in South Shroud, Quarrymill", "Chigoe Larva" },
                    { 228, 25, 4, "Akadaemia Anyder", "Clionid Larva" },
                    { 229, 25, 4, "Crafted by Level 60★ Carpenter", "Clockwork Barrow" },
                    { 230, 25, 4, "15,000 Wolf Mark from Storm Sergeant (Materia Provisioner).", "Clockwork Lantern" },
                    { 231, 25, 4, "Complete the Challenge Accepted achievement", "Clockwork Twintania" },
                    { 232, 25, 4, "Unspoiled Deposit, level 46-50 Miner", "Coblyn Larva" },
                    { 233, 25, 4, "Curiosity Killed the Coeurl quest in Aleport from Skribyld.", "Coeurl Kitten" },
                    { 234, 25, 4, "The Baldesion Arsenal", "Conditional Virtue" },
                    { 235, 25, 4, "Raid-wide drop in The Ridorana Lighthouse", "Construct 8" },
                    { 227, 25, 4, "Heavensward Pre-order", "Chocobo Chick Courier" },
                    { 692, 25, 5, "Purchased from Resident Caretaker for 1 Iron Voyage Spoil.", "Zu" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_CollectionTask_CategoryId",
                table: "CollectionTask",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_CollectionTask_CollectionTypeId",
                table: "CollectionTask",
                column: "CollectionTypeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CollectionTask");
        }
    }
}
