using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using XIVChecklist.Entities.Categories;
using XIVChecklist.Entities.Common;

namespace XIVChecklist.Data.Seed
{
    public static class SeedCategories
    {
        const int NEXT = 249;

        public static Category[] Categories = new Category[]
        {
            new Category(1, "Achievements", 1),
                new Category(2, "Battle", 2, 1),
                    new Category(3, "Battle", 3, 2),
                    new Category(4, "Dungeons", 3, 2),
                    new Category(5, "Trials", 3, 2),
                    new Category(6, "Raids", 3, 2),
                    new Category(7, "The Hunt", 3, 2),
                    new Category(8, "Treasure Hunt", 3, 2),
                    new Category(74, "FATEs", 3, 2),
                    new Category(76, "Hunting Log", 3, 2),
                new Category(9, "Character", 2, 1),
                    new Category(10, "General", 3, 9),
                    new Category(11, "Disciples of War", 3, 9),
                    new Category(12, "Disciples of Magic", 3, 9),
                    new Category(13, "Disciples of the Hand", 3, 9),
                    new Category(14, "Disciples of the Land", 3, 9),
                    new Category(15, "Commendation", 3, 9),
                    new Category(16, "Gold Saucer", 3, 9),
                new Category(17, "PvP", 2, 1),
                    new Category(18, "Frontline", 3, 17),
                    new Category(19, "General", 3, 17),
                    new Category(20, "The Wolves' Den", 3, 17),
                    new Category(67, "Rival Wings", 3, 17),
                    new Category(68, "Rankings", 3, 17),
                new Category(21, "Item", 2, 1),
                    new Category(22, "Item", 3, 21),
                    new Category(23, "Currency", 3, 21),
                    new Category(24, "Desynthesis", 3, 21),
                    new Category(25, "Collectibles", 3, 21),
                    new Category(26, "Materia", 3, 21),
                    new Category(27, "Relic", 3, 21),
                    new Category(28, "Zodiac", 3, 21),
                    new Category(29, "Anima", 3, 21),
                    new Category(30, "Deep Dungeon", 3, 21),
                    new Category(31, "Eureka Weapons", 3, 21),
                    new Category(78, "Orchestrion", 3, 21),
                new Category(32, "Crafting", 2, 1),
                    new Category(33, "Carpenter", 3, 32),
                    new Category(34, "Blacksmith", 3, 32),
                    new Category(35, "Armorer", 3, 32),
                    new Category(36, "Goldsmith", 3, 32),
                    new Category(37, "Leatherworker", 3, 32),
                    new Category(38, "Weaver", 3, 32),
                    new Category(39, "Alchemist", 3, 32),
                    new Category(40, "Culinarian", 3, 32),
                    new Category(73, "Shared", 3, 32),
                new Category(41, "Gathering", 2, 1),
                    new Category(42, "Miner", 3, 41),
                    new Category(43, "Botanist", 3, 41),
                    new Category(44, "Fisher", 3, 41),
                new Category(45, "Quests", 2, 1),
                    new Category(46, "Quests", 3, 45),
                    new Category(47, "Levequests", 3, 45),
                    new Category(48, "Beast Tribe", 3, 45),
                    new Category(77, "Main Story Quests", 3, 45),
                new Category(49, "Exploration", 2, 1),
                    new Category(50, "La Noscea", 3, 49),
                    new Category(51, "The Black Shroud", 3, 49),
                    new Category(52, "Thanalan", 3, 49),
                    new Category(53, "Coerthas", 3, 49),
                    new Category(54, "Mor Dhona", 3, 49),
                    new Category(55, "Abalathia's Spine", 3, 49),
                    new Category(56, "Dravania", 3, 49),
                    new Category(57, "Gyr Abania", 3, 49),
                    new Category(58, "Othard", 3, 49),
                    new Category(59, "Norvrandt", 3, 49),
                    new Category(60, "Duty", 3, 49),
                    new Category(61, "Sightseeing Log", 3, 49),
                new Category(62, "Grand Company", 2, 1),
                    new Category(63, "Grand Company", 3, 62),
                    new Category(64, "Maelstrom", 3, 62),
                    new Category(65, "Order of the Twin Adders", 3, 62),
                    new Category(66, "Immortal Flames", 3, 62),
            new Category(69, "Blue Mage", 1),
                new Category(70, "Masked Carnivale", 2, 69),
                new Category(71, "BLU Log", 2, 69),
                new Category(72, "Spellbook", 2, 69),
            new Category(79, "Collections", 1),
                new Category(80, "Aesthetics", 2, 79),
                new Category(81, "Bardings", 2, 79),
                new Category(82, "Emotes", 2, 79),
                new Category(83, "Minions", 2, 79),
                new Category(84, "Mounts", 2, 79),
                new Category(134, "Orchestrion", 2, 79),
                new Category(245, "Relic Weapons", 2, 79),
                    new Category(246, "Zodiac", 3, 245),
                    new Category(247, "Anima", 3, 245),
                    new Category(248, "Eurekan", 3, 245),
            new Category(85, "Crafting Logs", 1),
                new Category(86, "Alchemist", 2, 85),
                new Category(87, "Armorer", 2, 85),
                new Category(88, "Blacksmith", 2, 85),
                new Category(89, "Carpenter", 2, 85),
                new Category(90, "Culinarian", 2, 85),
                new Category(91, "Goldsmith", 2, 85),
                new Category(92, "Leatherworker", 2, 85),
                new Category(93, "Shared", 2, 85),
                new Category(94, "Weaver", 2, 85),
            new Category(95, "FATEs", 1),
                new Category(96, "Abalathia", 2, 95),
                new Category(97, "Black Shroud", 2, 95),
                new Category(98, "Coerthas", 2, 95),
                new Category(99, "Dravania", 2, 95),
                new Category(100, "Eureka", 2, 95),
                new Category(101, "Gyr Abania", 2, 95),
                new Category(102, "La Noscea", 2, 95),
                new Category(103, "Mor Dhona", 2, 95),
                new Category(104, "Norvrandt", 2, 95),
                new Category(105, "Othard", 2, 95),
                new Category(106, "Thanalan", 2, 95),
                new Category(107, "The Diadem", 2, 95),
            new Category(108, "Gathering Logs", 1),
                new Category(109, "Fish Guide", 2, 108),
                new Category(110, "Fishing", 2, 108),
                new Category(111, "Mining", 2, 108),
                new Category(112, "Botanist", 2, 108),
            new Category(113, "The Hunt", 1),
                new Category(114, "A Realm Reborn", 2, 113),
                new Category(115, "Heavensward", 2, 113),
                new Category(116, "Stormblood", 2, 113),
                new Category(117, "Shadowbringers", 2, 113),
            new Category(118, "Levequests", 1),
                new Category(119, "Battlecraft", 2, 118),
                new Category(120, "Tradecraft", 2, 118),
                new Category(121, "Fieldcraft", 2, 118),
            new Category(122, "Miscellaneous", 1),
                new Category(123, "Hunting Logs", 2, 122),
                new Category(124, "Sightseeing Logs", 2, 122),
            new Category(125, "MSQ", 1),
                new Category(126, "Seventh Umbral Era", 2, 125),
                new Category(127, "Seventh Astral Era", 2, 125),
                new Category(128, "Heavensward", 2, 125),
                new Category(129, "Dragonsong War", 2, 125),
                new Category(130, "Stormblood", 2, 125),
                new Category(131, "The Legend Returns", 2, 125),
                new Category(132, "Shadowbringers", 2, 125),
                new Category(133, "Post-Shadowbringers", 2, 125),
            new Category(135, "PvE", 1),
                new Category(136, "Dungeons", 2, 135),
                new Category(137, "Guildhests", 2, 135),
                new Category(138, "Raids", 2, 135),
                new Category(139, "Trials", 2, 135),
            new Category(140, "Side Quests", 1),
                new Category(141, "Abalathia's Spine", 2, 140),
                new Category(142, "Amh Araeng", 2, 140),
                new Category(143, "Beast Tribe", 2, 140),
                    new Category(144, "Amalj'aa", 3, 143),
                    new Category(145, "Ixal", 3, 143),
                    new Category(146, "Kobold", 3, 143),
                    new Category(147, "Sahagin", 3, 143),
                    new Category(148, "Sylph", 3, 143),
                    new Category(149, "Allied (A Realm Reborn)", 3, 143),
                    new Category(150, "Moogle", 3, 143),
                    new Category(151, "Vanu Vanu", 3, 143),
                    new Category(152, "Vath", 3, 143),
                    new Category(153, "Allied (Heavensward)", 3, 143),
                    new Category(154, "Ananta", 3, 143),
                    new Category(155, "Kojin", 3, 143),
                    new Category(156, "Namazu", 3, 143),
                    new Category(157, "Allied (Stormblood)", 3, 143),
                    new Category(158, "Pixie", 3, 143),
                new Category(159, "Black Shroud", 2, 140),
                new Category(160, "Chronicles of a New Era", 2, 140),
                new Category(161, "Class Quests", 2, 140),
                    new Category(162, "Tank", 3, 161),
                    new Category(163, "DPS", 3, 161),
                    new Category(164, "Healer", 3, 161),
                    new Category(165, "Archer", 3, 161),
                    new Category(166, "Gladiator", 3, 161),
                    new Category(167, "Lancer", 3, 161),
                    new Category(168, "Marauder", 3, 161),
                    new Category(169, "Pugilist", 3, 161),
                    new Category(170, "Rogue", 3, 161),
                    new Category(171, "Arcanist", 3, 161),
                    new Category(172, "Conjurer", 3, 161),
                    new Category(173, "Thaumaturge", 3, 161),
                    new Category(174, "Alchemist", 3, 161),
                    new Category(175, "Armorer", 3, 161),
                    new Category(176, "Blacksmith", 3, 161),
                    new Category(177, "Carpenter", 3, 161),
                    new Category(178, "Culinarian", 3, 161),
                    new Category(179, "Goldsmith", 3, 161),
                    new Category(180, "Leatherworker", 3, 161),
                    new Category(181, "Weaver", 3, 161),
                    new Category(182, "Botanist", 3, 161),
                    new Category(183, "Fisher", 3, 161),
                    new Category(184, "Miner", 3, 161),
                new Category(185, "Coerthas", 2, 140),
                new Category(186, "Crystalline Mean", 2, 140),
                new Category(187, "Dravania", 2, 140),
                new Category(188, "Grand Company", 2, 140),
                new Category(189, "Gyr Abania", 2, 140),
                new Category(190, "Il Mheg", 2, 140),
                new Category(191, "Ishgard", 2, 140),
                new Category(192, "Job Quests", 2, 140),
                    new Category(193, "Bard", 3, 192),
                    new Category(194, "Dancer", 3, 192),
                    new Category(195, "Dark Knight", 3, 192),
                    new Category(196, "Dragoon", 3, 192),
                    new Category(197, "Gunbreaker", 3, 192),
                    new Category(198, "Machinist", 3, 192),
                    new Category(199, "Monk", 3, 192),
                    new Category(200, "Ninja", 3, 192),
                    new Category(201, "Paladin", 3, 192),
                    new Category(202, "Samurai", 3, 192),
                    new Category(203, "Warrior", 3, 192),
                    new Category(204, "Astrologian", 3, 192),
                    new Category(205, "Black Mage", 3, 192),
                    new Category(206, "Blue Mage", 3, 192),
                    new Category(207, "Red Mage", 3, 192),
                    new Category(208, "Scholar", 3, 192),
                    new Category(209, "Summoner", 3, 192),
                    new Category(210, "White Mage", 3, 192),
                new Category(211, "Kholusia", 2, 140),
                new Category(212, "Kugane", 2, 140),
                new Category(213, "La Noscea", 2, 140),
                new Category(214, "Lakeland", 2, 140),
                new Category(215, "Mor Dhona", 2, 140),
                new Category(216, "Othard", 2, 140),
                new Category(217, "Rak'tika", 2, 140),
                new Category(218, "Role Quests", 2, 140),
                    new Category(219, "Tank", 3, 218),
                    new Category(220, "Physical DPS", 3, 218),
                    new Category(221, "Healer", 3, 218),
                    new Category(222, "Magical DPS", 3, 218),
                    new Category(244, "Epilogue", 3, 218),
                new Category(223, "Side Story", 2, 140),
                new Category(224, "Tempest", 2, 140),
                new Category(225, "Thanalan", 2, 140),
            new Category(241, "Triple Triad", 1),
                new Category(242, "Cards", 2, 241),
                new Category(243, "Opponents", 2, 241)
        };

        public static int GetCategoryId(string name)
        {
            try
            {
                return Categories.FirstOrDefault(
                    x => x.Name.ToLower() == name.ToLower() && x.ParentCategoryId != 1
                ).Id;
            }
            catch(Exception ex)
            {
                throw new Exception("Category not found: " + name);
            }
        }

        public static int GetCategoryId(string parentName, string childName)
        {
            try
            {
                var parentCategory = Categories.FirstOrDefault(
                    x => x.Name.ToLower() == parentName.ToLower() && x.Position <= 2
                );

                return Categories.FirstOrDefault(
                    x => x.Name.ToLower() == childName.ToLower() && x.ParentCategoryId == parentCategory.Id
                ).Id;
            }
            catch(Exception ex)
            {
                throw new Exception("Category not found: " + parentName + " > " + childName);
            }
        }
    }
}
